-- V10 (REQ-0004, rediseno del modulo de seguridad pedido por el usuario):
-- modelo minimo: usuario, grupo, usuario_grupo (integrantes), permiso_grupo (como
-- perfil funcional) y permiso_usuario (ya existente). Los permisos efectivos de un
-- usuario = permisos directos UNION permisos de sus grupos ACTIVOS.
-- Ademas: email y telefono en usuario (base para validacion de dos pasos y alertas
-- de acceso fallido; el envio requiere SMTP, fase siguiente).

CREATE TABLE grupo (
  grupo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo varchar(30) NOT NULL UNIQUE,
  descripcion varchar(120) NOT NULL,
  estado varchar(10) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO')),
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  version bigint NOT NULL DEFAULT 0
);

CREATE TABLE usuario_grupo (
  usuario_grupo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario bigint NOT NULL REFERENCES usuario,
  grupo   bigint NOT NULL REFERENCES grupo,
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  version bigint NOT NULL DEFAULT 0,
  UNIQUE (usuario, grupo)
);

CREATE TABLE permiso_grupo (
  permiso_grupo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  grupo    bigint      NOT NULL REFERENCES grupo,
  pantalla varchar(60) NOT NULL,
  accion   varchar(30) NOT NULL CHECK (accion IN
           ('OPERAR','VER','CREAR','EDITAR','INACTIVAR','REACTIVAR','EXPORTAR','VER_AUDITORIA')),
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  version bigint NOT NULL DEFAULT 0,
  UNIQUE (grupo, pantalla, accion)
);

ALTER TABLE usuario ADD COLUMN IF NOT EXISTS email varchar(180);
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS telefono varchar(30);

INSERT INTO entidad (entidad, codigo, descripcion, usuario_creacion, fecha_creacion) VALUES
  ('PANTALLAS', 'grupos', 'Grupos de seguridad', 'sistema', now())
ON CONFLICT (entidad, codigo) DO NOTHING;

-- Grupo de ejemplo listo para usar: operadores de articulos
INSERT INTO grupo (codigo, descripcion, usuario_creacion, fecha_creacion)
VALUES ('OPER_ARTICULOS', 'Operadores de artículos', 'sistema', now());
INSERT INTO permiso_grupo (grupo, pantalla, accion, usuario_creacion, fecha_creacion)
SELECT grupo, 'articulos', 'OPERAR', 'sistema', now() FROM grupo WHERE codigo = 'OPER_ARTICULOS';
