-- ============================================================================
-- SGInmo Web — V1: esquema inicial (REQ-0003) — REVISION 4
-- Obs aplicadas (2026-07-05):
--   5: articulo con FK a impuesto (el % vive en la tabla impuesto; el detalle guarda snapshot)
--   6: articulo_detalle eliminada (absorbida por articulo_propiedad)
--   8: tabla empresa ELIMINADA — la empresa operadora ES una persona_juridica;
--      toda FK "empresa" referencia persona_juridica
--   9: sucursal referencia persona_juridica
--  10: columnas boolean "activo" renombradas a "estado" ACTIVO/INACTIVO en TODAS las
--      tablas (usuario, forma_pago, articulo, persona) — "activo" queda solo para la tabla activo
--  11: archivo_adjunto con FKs reales (activo/operacion/documento/persona/cobro)
--   7 (persona): PENDIENTE de aclaracion del usuario
-- ============================================================================

-- ── Nucleo parametrico ──────────────────────────────────────────────────────

CREATE TABLE parametro_sistema (
  clave        varchar(60) PRIMARY KEY,
  valor        varchar(120) NOT NULL,
  descripcion  varchar(180) NOT NULL,
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz
);

CREATE TABLE entidad (
  entidad      varchar(40)  NOT NULL,
  codigo       varchar(40)  NOT NULL,
  descripcion  varchar(180) NOT NULL,
  valor_texto  varchar(250),
  estado       varchar(10)  NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO')),
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  PRIMARY KEY (entidad, codigo)
);

CREATE TABLE ubicacion_geografica (
  ubicacion_geografica bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  padre        bigint REFERENCES ubicacion_geografica,
  nombre       varchar(150) NOT NULL,
  nivel_lista  varchar(40) NOT NULL DEFAULT 'NIVELES_UBICACION',
  nivel_codigo varchar(40) NOT NULL,
  codigo_oficial varchar(10) UNIQUE,       -- codigo INE (DPA): permite re-importar actualizaciones por upsert
  estado       varchar(10) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO')),
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  FOREIGN KEY (nivel_lista, nivel_codigo) REFERENCES entidad,
  UNIQUE (padre, nombre, nivel_codigo)
);
CREATE INDEX ix_ubicacion_padre ON ubicacion_geografica (padre);

CREATE TABLE moneda (
  moneda       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion  varchar(120) NOT NULL,
  simbolo      varchar(20)  NOT NULL,
  tipo_moneda  varchar(20)  NOT NULL CHECK (tipo_moneda IN ('LOCAL','EXTRANJERA')),
  precision_decimales smallint NOT NULL DEFAULT 0,
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz
);

CREATE TABLE forma_pago (
  forma_pago  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion varchar(120) NOT NULL,
  codigo      varchar(20)  NOT NULL UNIQUE,
  dias        int,
  por_defecto boolean NOT NULL DEFAULT false,
  requiere_emisor boolean NOT NULL DEFAULT false,
  requiere_procesador boolean NOT NULL DEFAULT false,
  requiere_numero boolean NOT NULL DEFAULT false,
  requiere_serie boolean NOT NULL DEFAULT false,
  requiere_vencimiento boolean NOT NULL DEFAULT false,
  requiere_cuenta boolean NOT NULL DEFAULT false,
  requiere_referencia boolean NOT NULL DEFAULT false,
  requiere_cobrador boolean NOT NULL DEFAULT false,
  requiere_fecha_deposito boolean NOT NULL DEFAULT false,
  requiere_numero_deposito boolean NOT NULL DEFAULT false,
  requiere_estado_deposito boolean NOT NULL DEFAULT false,
  requiere_motivo_rechazo boolean NOT NULL DEFAULT false,
  requiere_nota_credito boolean NOT NULL DEFAULT false,
  estado varchar(10) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO')),
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz
);

CREATE TABLE impuesto (
  impuesto     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion  varchar(120) NOT NULL,
  porcentaje_impuesto numeric(5,2) NOT NULL,
  factor_discriminado numeric(15,2) NOT NULL,
  factor_impuesto     numeric(15,2) NOT NULL,
  estado varchar(10) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO')),
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz
);

-- ── Maestro de articulos (productos y servicios; conceptos de dinero) ──────

CREATE TABLE articulo (
  articulo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo varchar(25) NOT NULL UNIQUE,
  descripcion varchar(150) NOT NULL,
  tipo varchar(10) NOT NULL CHECK (tipo IN ('PRODUCTO','SERVICIO')),
  impuesto bigint NOT NULL REFERENCES impuesto,      -- [Obs 5] el % y factores viven en impuesto
  categoria_lista varchar(40) DEFAULT 'TIPOS_ARTICULO',
  categoria_codigo varchar(40),
  unidad_medida_lista varchar(40) DEFAULT 'UNIDADES_MEDIDA',
  unidad_medida_codigo varchar(40),
  presentacion_lista varchar(40) DEFAULT 'PRESENTACIONES',
  presentacion_codigo varchar(40),
  clasificacion varchar(20),
  marca_lista varchar(40) DEFAULT 'MARCAS',
  marca_codigo varchar(40),
  modelo_lista varchar(40) DEFAULT 'MODELOS',
  modelo_codigo varchar(40),
  familia_lista varchar(40) DEFAULT 'FAMILIAS_ARTICULO',
  familia_codigo varchar(40),
  grupo_lista varchar(40) DEFAULT 'GRUPOS_ARTICULO',
  grupo_codigo varchar(40),
  subgrupo_lista varchar(40) DEFAULT 'SUBGRUPOS_ARTICULO',
  subgrupo_codigo varchar(40),
  procedencia_lista varchar(40) DEFAULT 'PROCEDENCIAS',
  procedencia_codigo varchar(40),
  codigo_barra varchar(50),
  codigo_interno varchar(25),
  precio_unitario numeric(15,2) NOT NULL DEFAULT 0,
  precio_unitario_ext numeric(15,2),
  stock_minimo numeric(15,3),
  stock_maximo numeric(15,3),
  porcentaje_stock_minimo numeric(5,2),
  proveedor bigint,                        -- FK a persona (se agrega tras crear persona)
  ultimo_costo numeric(15,2),
  costo_moneda_ext numeric(15,2),
  proximo_vencimiento date,
  cuenta varchar(50),
  tipo_movimiento varchar(10) CHECK (tipo_movimiento IN ('INGRESO','EGRESO','DESCUENTO')),
  modifica_estado boolean NOT NULL DEFAULT false,
  aplicacion varchar(30) UNIQUE,
  estado varchar(10) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO')),
  observacion varchar(250),
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  FOREIGN KEY (categoria_lista, categoria_codigo) REFERENCES entidad,
  FOREIGN KEY (unidad_medida_lista, unidad_medida_codigo) REFERENCES entidad,
  FOREIGN KEY (presentacion_lista, presentacion_codigo) REFERENCES entidad,
  FOREIGN KEY (marca_lista, marca_codigo) REFERENCES entidad,
  FOREIGN KEY (modelo_lista, modelo_codigo) REFERENCES entidad,
  FOREIGN KEY (familia_lista, familia_codigo) REFERENCES entidad,
  FOREIGN KEY (grupo_lista, grupo_codigo) REFERENCES entidad,
  FOREIGN KEY (subgrupo_lista, subgrupo_codigo) REFERENCES entidad,
  FOREIGN KEY (procedencia_lista, procedencia_codigo) REFERENCES entidad
);

-- [Obs 6] articulo_detalle eliminada: codigo de barra por variante, color, talle, etc.
-- se cargan como propiedades del articulo (lista PROPIEDADES_ARTICULO: COLOR, TALLE, CODIGO_BARRA_VARIANTE...).
CREATE TABLE articulo_propiedad (
  articulo_propiedad bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  articulo bigint NOT NULL REFERENCES articulo,
  propiedad_lista varchar(40) NOT NULL DEFAULT 'PROPIEDADES_ARTICULO',
  propiedad_codigo varchar(40) NOT NULL,
  valor varchar(100),
  numero numeric(15,2),
  fecha date,
  referencia_lista varchar(40),
  referencia_codigo varchar(40),
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  FOREIGN KEY (propiedad_lista, propiedad_codigo) REFERENCES entidad,
  FOREIGN KEY (referencia_lista, referencia_codigo) REFERENCES entidad,
  UNIQUE (articulo, propiedad_lista, propiedad_codigo)
);

CREATE TABLE articulo_costo (
  articulo_costo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  articulo bigint NOT NULL REFERENCES articulo,
  fecha date NOT NULL,
  costo numeric(15,2),
  costo_ext numeric(15,2),
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  UNIQUE (articulo, fecha)
);

-- ── Personas: datos basicos + especializacion + roles multiples ────────────
-- [Obs 7 PENDIENTE: definir con el usuario la forma final de la clave persona/fisica/juridica]

CREATE TABLE persona (
  persona bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_personeria varchar(10) NOT NULL CHECK (tipo_personeria IN ('FISICA','JURIDICA')),
  nombre varchar(180) NOT NULL,            -- nombre visible: nombre completo o razon social
  numero_documento varchar(20) NOT NULL UNIQUE,
  digito_verificador char(1),
  tipo_documento_lista varchar(40) DEFAULT 'TIPOS_DOCUMENTOS_IDENTIDAD',
  tipo_documento_codigo varchar(40),
  es_contribuyente boolean NOT NULL DEFAULT false,
  clasificacion_fiscal varchar(20),
  direccion varchar(180), telefono varchar(20), email varchar(180),
  ubicacion bigint REFERENCES ubicacion_geografica,
  ubicacion_url varchar(250),
  estado varchar(10) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO')),
  observacion text,
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  FOREIGN KEY (tipo_documento_lista, tipo_documento_codigo) REFERENCES entidad
);

CREATE TABLE persona_fisica (
  persona bigint PRIMARY KEY REFERENCES persona,
  nombres varchar(120) NOT NULL,
  apellidos varchar(120) NOT NULL,
  sexo varchar(10) CHECK (sexo IN ('MASCULINO','FEMENINO')),
  fecha_nacimiento date,
  estado_civil_lista varchar(40) DEFAULT 'ESTADOS_CIVILES',
  estado_civil_codigo varchar(40),
  nacionalidad varchar(80),
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  FOREIGN KEY (estado_civil_lista, estado_civil_codigo) REFERENCES entidad
);

CREATE TABLE persona_juridica (
  persona bigint PRIMARY KEY REFERENCES persona,
  razon_social varchar(180) NOT NULL,
  nombre_fantasia varchar(120),
  fecha_constitucion date,
  representante_legal bigint REFERENCES persona,
  actividad_lista varchar(40) DEFAULT 'ACTIVIDADES_ECONOMICAS',
  actividad_codigo varchar(40),
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  FOREIGN KEY (actividad_lista, actividad_codigo) REFERENCES entidad
);

CREATE TABLE persona_rol (
  persona_rol bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  persona bigint NOT NULL REFERENCES persona,
  rol_lista varchar(40) NOT NULL DEFAULT 'ROLES_PERSONA',
  rol_codigo varchar(40) NOT NULL,
  estado varchar(10) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO')),
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  FOREIGN KEY (rol_lista, rol_codigo) REFERENCES entidad,
  UNIQUE (persona, rol_lista, rol_codigo)
);

ALTER TABLE articulo
  ADD CONSTRAINT fk_articulo_proveedor FOREIGN KEY (proveedor) REFERENCES persona;

-- ── Organizacion ────────────────────────────────────────────────────────────
-- [Obs 8] La tabla empresa fue ELIMINADA: la empresa operadora ES una persona_juridica.
-- Toda columna "empresa" del esquema referencia persona_juridica(persona).

CREATE TABLE sucursal (                    -- [Obs 9]
  sucursal bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  persona_juridica bigint NOT NULL REFERENCES persona_juridica,
  descripcion varchar(180) NOT NULL,
  direccion varchar(180) NOT NULL, telefono varchar(20) NOT NULL,
  por_defecto boolean NOT NULL DEFAULT false,
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz
);

CREATE TABLE usuario (
  usuario bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_usuario varchar(20) NOT NULL UNIQUE,
  password_hash varchar(100) NOT NULL,
  perfil varchar(20) NOT NULL CHECK (perfil IN ('ADMINISTRADOR','USUARIO')),
  estado varchar(10) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO')),  -- [Obs 10]
  empresa bigint NOT NULL REFERENCES persona_juridica,
  persona bigint REFERENCES persona,
  intentos_fallidos smallint NOT NULL DEFAULT 0,
  bloqueado_hasta timestamptz,
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz
);

-- ── Activos: recursivo; el tipo define, los atributos complementan ─────────

CREATE TABLE activo (
  activo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  padre bigint REFERENCES activo,
  nombre varchar(180) NOT NULL,
  tipo_lista varchar(40) NOT NULL DEFAULT 'TIPOS_ACTIVO',
  tipo_codigo varchar(40) NOT NULL,
  empresa bigint REFERENCES persona_juridica,
  ubicacion bigint REFERENCES ubicacion_geografica,
  direccion varchar(250),
  precio_venta numeric(15,2) NOT NULL DEFAULT 0,
  comision_venta numeric(5,2) NOT NULL DEFAULT 0,
  precio_alquiler numeric(15,2) NOT NULL DEFAULT 0,
  comision_alquiler numeric(5,2) NOT NULL DEFAULT 0,
  estado varchar(20) NOT NULL DEFAULT 'LIBRE' CHECK (estado IN ('LIBRE','OCUPADA','VENDIDA')),
  cuenta_catastral varchar(120), numero_finca varchar(20),
  numero_lote varchar(20), numero_manzana varchar(20),
  observacion varchar(250),
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  FOREIGN KEY (tipo_lista, tipo_codigo) REFERENCES entidad
);
CREATE INDEX ix_activo_padre ON activo (padre);

CREATE TABLE atributo (
  atributo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  grupo_lista varchar(40) NOT NULL DEFAULT 'GRUPOS_ATRIBUTOS',
  grupo_codigo varchar(40) NOT NULL,
  descripcion varchar(120) NOT NULL,
  tipo_dato varchar(10) NOT NULL CHECK (tipo_dato IN ('TEXTO','NUMERO','BOOLEANO','FECHA')),
  estado varchar(10) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO')),
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  FOREIGN KEY (grupo_lista, grupo_codigo) REFERENCES entidad,
  UNIQUE (grupo_codigo, descripcion)
);

CREATE TABLE atributo_por_tipo (
  atributo_por_tipo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  atributo bigint NOT NULL REFERENCES atributo,
  tipo_lista varchar(40) NOT NULL DEFAULT 'TIPOS_ACTIVO',
  tipo_codigo varchar(40) NOT NULL,
  obligatorio boolean NOT NULL DEFAULT false,
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  FOREIGN KEY (tipo_lista, tipo_codigo) REFERENCES entidad,
  UNIQUE (atributo, tipo_lista, tipo_codigo)
);

CREATE TABLE activo_atributo (
  activo_atributo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activo bigint NOT NULL REFERENCES activo,
  atributo bigint NOT NULL REFERENCES atributo,
  valor text,
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  UNIQUE (activo, atributo)
);

CREATE TABLE activo_propietario (
  activo_propietario bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activo bigint NOT NULL REFERENCES activo,
  propietario bigint NOT NULL REFERENCES persona,
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  UNIQUE (activo, propietario)
);

-- ── Operaciones ─────────────────────────────────────────────────────────────

CREATE TABLE operacion (
  operacion bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_operacion date NOT NULL,
  tipo_operacion varchar(10) NOT NULL CHECK (tipo_operacion IN ('ALQUILER','VENTA')),
  cliente bigint NOT NULL REFERENCES persona,
  vendedor bigint REFERENCES persona,
  activo bigint NOT NULL REFERENCES activo,
  fecha_inicio_contrato date NOT NULL,
  fecha_fin_contrato date, fecha_finalizacion date, fecha_renovacion date,
  plazo int,
  precio numeric(15,2) NOT NULL,
  monto_total_operacion numeric(15,2) NOT NULL,
  monto_total_letras text,
  garantia numeric(15,2) NOT NULL DEFAULT 0,
  estado varchar(20) NOT NULL DEFAULT 'VIGENTE' CHECK (estado IN ('VIGENTE','FINALIZADO')),
  empresa bigint NOT NULL REFERENCES persona_juridica,
  sucursal bigint NOT NULL REFERENCES sucursal,
  moneda bigint NOT NULL REFERENCES moneda,
  tipo_contrato_lista varchar(40) DEFAULT 'TIPOS_CONTRATOS', tipo_contrato_codigo varchar(40),
  tipo_financiacion_lista varchar(40) DEFAULT 'TIPOS_FINANCIACIONES', tipo_financiacion_codigo varchar(40),
  condicion_operacion varchar(10) NOT NULL CHECK (condicion_operacion IN ('CONTADO','CREDITO')),
  aviso_renovacion boolean NOT NULL DEFAULT false,
  dia_pago smallint,
  monto_mora numeric(15,2) NOT NULL DEFAULT 0,
  dias_gracia smallint,
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  FOREIGN KEY (tipo_contrato_lista, tipo_contrato_codigo) REFERENCES entidad,
  FOREIGN KEY (tipo_financiacion_lista, tipo_financiacion_codigo) REFERENCES entidad
);
CREATE INDEX ix_operacion_estado ON operacion (estado, empresa);

CREATE TABLE rescision (
  rescision bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operacion bigint NOT NULL REFERENCES operacion,
  fecha date NOT NULL,
  tipo varchar(30),
  monto numeric(15,2) NOT NULL DEFAULT 0,
  observacion text,
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz
);

-- ── Dinero: documento + detalle + cuotas + cobros (patron Gestion) ─────────

CREATE TABLE rango_comprobante (
  rango_comprobante bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa bigint NOT NULL REFERENCES persona_juridica,
  tipo_lista varchar(40) NOT NULL DEFAULT 'TIPOS_DOCUMENTO',
  tipo_codigo varchar(40) NOT NULL,
  serie varchar(20) NOT NULL,
  numero_desde bigint NOT NULL,
  numero_actual bigint NOT NULL,
  numero_hasta bigint NOT NULL,
  fecha_desde date, fecha_vencimiento date,
  timbrado varchar(25),
  estado varchar(10) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO')),
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  FOREIGN KEY (tipo_lista, tipo_codigo) REFERENCES entidad,
  UNIQUE (empresa, tipo_codigo, serie, numero_desde)
);

CREATE TABLE documento (
  documento bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa bigint NOT NULL REFERENCES persona_juridica,
  tipo_lista varchar(40) NOT NULL DEFAULT 'TIPOS_DOCUMENTO',
  tipo_codigo varchar(40) NOT NULL,
  serie varchar(20) NOT NULL,
  numero bigint NOT NULL,
  fecha date NOT NULL,
  fecha_vencimiento date,
  persona bigint REFERENCES persona,
  sucursal bigint REFERENCES sucursal,
  moneda bigint NOT NULL REFERENCES moneda,
  cotizacion numeric(15,5) NOT NULL DEFAULT 1,
  total numeric(15,2) NOT NULL DEFAULT 0,
  saldo numeric(15,2) NOT NULL DEFAULT 0,
  direccion_dinero varchar(10) NOT NULL CHECK (direccion_dinero IN ('ENTRADA','SALIDA')),
  estado varchar(20) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE','CANCELADO','ANULADO')),
  timbrado varchar(25),
  documento_ref bigint REFERENCES documento,
  observacion varchar(250),
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  FOREIGN KEY (tipo_lista, tipo_codigo) REFERENCES entidad,
  UNIQUE (empresa, tipo_codigo, serie, numero),
  CHECK (saldo >= 0 AND saldo <= total)
);

CREATE TABLE documento_detalle (
  documento_detalle bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  documento bigint NOT NULL REFERENCES documento ON DELETE CASCADE,
  numero_item int NOT NULL,
  concepto varchar(250) NOT NULL,
  articulo bigint REFERENCES articulo,
  cantidad numeric(15,3) NOT NULL DEFAULT 1,
  precio_unitario numeric(15,2) NOT NULL DEFAULT 0,
  exentas numeric(15,2) NOT NULL DEFAULT 0,
  gravadas numeric(15,2) NOT NULL DEFAULT 0,
  porcentaje_impuesto numeric(5,2) NOT NULL DEFAULT 0,   -- snapshot del impuesto del articulo al facturar
  impuestos numeric(15,2) NOT NULL DEFAULT 0,
  monto numeric(15,2) NOT NULL,
  saldo numeric(15,2) NOT NULL DEFAULT 0,
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  UNIQUE (documento, numero_item)
);

CREATE TABLE cronograma_cuota (
  cronograma_cuota bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operacion bigint NOT NULL REFERENCES operacion,
  documento bigint REFERENCES documento,
  numero_cuota int NOT NULL,
  fecha_vencimiento date NOT NULL,
  monto numeric(15,2) NOT NULL,
  saldo numeric(15,2) NOT NULL DEFAULT 0,
  estado varchar(20) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE','CANCELADO')),
  moneda bigint NOT NULL REFERENCES moneda,
  fecha_cancelacion date,
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  UNIQUE (operacion, numero_cuota)
);
CREATE INDEX ix_cuota_pendiente ON cronograma_cuota (estado, fecha_vencimiento);

CREATE TABLE planilla (
  planilla bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa bigint NOT NULL REFERENCES persona_juridica,
  sucursal bigint NOT NULL REFERENCES sucursal,
  usuario_apertura varchar(20) NOT NULL,
  fecha_apertura date NOT NULL, hora_apertura timestamptz NOT NULL,
  monto_apertura numeric(15,2) NOT NULL DEFAULT 0,
  usuario_cierre varchar(20), fecha_cierre date, hora_cierre timestamptz,
  monto_cobro numeric(15,2) NOT NULL DEFAULT 0,
  estado varchar(10) NOT NULL DEFAULT 'ABIERTA' CHECK (estado IN ('ABIERTA','CERRADA')),
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz
);

CREATE TABLE cobro (
  cobro bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa bigint NOT NULL REFERENCES persona_juridica,
  sucursal bigint NOT NULL REFERENCES sucursal,
  planilla bigint NOT NULL REFERENCES planilla,
  forma_pago bigint REFERENCES forma_pago,
  persona bigint REFERENCES persona,
  pagador bigint REFERENCES persona,
  cajero varchar(20),
  fecha date NOT NULL,
  hora timestamptz NOT NULL,
  monto numeric(15,2) NOT NULL DEFAULT 0,
  moneda bigint NOT NULL REFERENCES moneda,
  monto_ext numeric(15,2),
  cotizacion numeric(15,5) NOT NULL DEFAULT 1,
  moneda_vuelto bigint REFERENCES moneda,
  vuelto numeric(15,2) NOT NULL DEFAULT 0,
  recibo_documento bigint REFERENCES documento,
  factura_documento bigint REFERENCES documento,
  concepto varchar(255),
  estado varchar(10) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','ANULADO')),
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz
);

CREATE TABLE cobro_detalle (
  cobro_detalle bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cobro bigint NOT NULL REFERENCES cobro,
  secuencia int NOT NULL,
  documento bigint NOT NULL REFERENCES documento,
  monto numeric(15,2) NOT NULL,
  monto_ext numeric(15,2),
  cotizacion numeric(15,5) NOT NULL DEFAULT 1,
  estado varchar(10) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','ANULADO')),
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  UNIQUE (cobro, secuencia)
);

CREATE TABLE dato_cobro (
  dato_cobro bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cobro bigint NOT NULL REFERENCES cobro,
  emisor_lista varchar(40) DEFAULT 'EMISORES', emisor_codigo varchar(40),
  procesador_lista varchar(40) DEFAULT 'PROCESADORES', procesador_codigo varchar(40),
  numero varchar(25), serie varchar(20),
  cuenta_corriente varchar(50),
  fecha_vencimiento date,
  referencia varchar(50), observacion varchar(100),
  recibo varchar(20),
  cobrador bigint REFERENCES persona,
  fecha_deposito date, numero_deposito varchar(25),
  estado_deposito varchar(10),
  motivo_rechazo_lista varchar(40) DEFAULT 'MOTIVOS_RECHAZO', motivo_rechazo_codigo varchar(40),
  ntcr_documento bigint REFERENCES documento,
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  FOREIGN KEY (emisor_lista, emisor_codigo) REFERENCES entidad,
  FOREIGN KEY (procesador_lista, procesador_codigo) REFERENCES entidad,
  FOREIGN KEY (motivo_rechazo_lista, motivo_rechazo_codigo) REFERENCES entidad
);

CREATE TABLE detalle_afectado (
  detalle_afectado bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cobro_detalle bigint NOT NULL REFERENCES cobro_detalle,
  documento_detalle bigint NOT NULL REFERENCES documento_detalle,
  monto numeric(15,2) NOT NULL,
  estado varchar(10) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','ANULADO')),
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz
);

CREATE TABLE anulacion (
  anulacion bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa bigint NOT NULL REFERENCES persona_juridica,
  documento bigint REFERENCES documento,
  cobro bigint REFERENCES cobro,
  motivo_lista varchar(40) NOT NULL DEFAULT 'MOTIVOS_ANULACION', motivo_codigo varchar(40) NOT NULL,
  fecha timestamptz NOT NULL,
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  FOREIGN KEY (motivo_lista, motivo_codigo) REFERENCES entidad
);

CREATE TABLE ingreso_egreso (
  ingreso_egreso bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  documento bigint REFERENCES documento,
  fecha date NOT NULL,
  tipo varchar(10) NOT NULL CHECK (tipo IN ('INGRESO','EGRESO')),
  monto numeric(15,2) NOT NULL,
  saldo numeric(15,2) NOT NULL DEFAULT 0,
  estado varchar(20) NOT NULL CHECK (estado IN ('PENDIENTE','CANCELADO','ANULADO','VENCIDO')),
  articulo bigint NOT NULL REFERENCES articulo,
  persona bigint REFERENCES persona,
  activo bigint REFERENCES activo,
  operacion bigint REFERENCES operacion,
  tipo_imputacion_lista varchar(40) DEFAULT 'TIPOS_IMPUTACION', tipo_imputacion_codigo varchar(40),
  forma_pago bigint REFERENCES forma_pago,
  empresa bigint NOT NULL REFERENCES persona_juridica,
  observacion text,
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  FOREIGN KEY (tipo_imputacion_lista, tipo_imputacion_codigo) REFERENCES entidad
);

CREATE TABLE liquidacion (
  liquidacion bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operacion bigint NOT NULL UNIQUE REFERENCES operacion,
  documento bigint REFERENCES documento,
  fecha date NOT NULL, fecha_fiscalizacion date NOT NULL,
  entrego_llaves boolean NOT NULL DEFAULT false,
  total_garantia numeric(15,2) NOT NULL,
  total_gastos numeric(15,2) NOT NULL,
  saldo numeric(15,2) NOT NULL,
  motivo_lista varchar(40) DEFAULT 'MOTIVOS_LIQUIDACION', motivo_codigo varchar(40),
  observacion varchar(180),
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  FOREIGN KEY (motivo_lista, motivo_codigo) REFERENCES entidad
);

CREATE TABLE liquidacion_detalle (
  liquidacion_detalle bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  liquidacion bigint NOT NULL REFERENCES liquidacion ON DELETE CASCADE,
  numero_item int NOT NULL,
  articulo bigint NOT NULL REFERENCES articulo,
  monto numeric(15,2) NOT NULL,
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz
);

-- ── Adjuntos [Obs 11: relacionada con FKs reales] ──────────────────────────

CREATE TABLE archivo_adjunto (
  archivo_adjunto bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activo bigint REFERENCES activo,
  operacion bigint REFERENCES operacion,
  documento bigint REFERENCES documento,
  persona bigint REFERENCES persona,
  cobro bigint REFERENCES cobro,
  nombre_original varchar(250) NOT NULL,
  ruta varchar(500) NOT NULL,
  tipo_mime varchar(100), tamanio_bytes bigint,
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  CHECK (activo IS NOT NULL OR operacion IS NOT NULL OR documento IS NOT NULL
         OR persona IS NOT NULL OR cobro IS NOT NULL)
);
CREATE INDEX ix_adjunto_activo ON archivo_adjunto (activo);
CREATE INDEX ix_adjunto_operacion ON archivo_adjunto (operacion);
CREATE INDEX ix_adjunto_documento ON archivo_adjunto (documento);

-- ── Vista unificadora de personas [Obs 7: decision del usuario] ────────────
-- Equivalente del v_ente de Gestion: una sola consulta con los datos de la persona
-- y su especializacion (fisica o juridica), para grillas, buscadores y reportes.

CREATE VIEW v_persona AS
SELECT p.persona,
       p.tipo_personeria,
       p.nombre,
       p.numero_documento,
       p.digito_verificador,
       p.tipo_documento_codigo,
       p.es_contribuyente,
       p.clasificacion_fiscal,
       p.direccion, p.telefono, p.email,
       p.ubicacion, p.ubicacion_url,
       p.estado,
       pf.nombres, pf.apellidos, pf.sexo, pf.fecha_nacimiento,
       pf.estado_civil_codigo, pf.nacionalidad,
       pj.razon_social, pj.nombre_fantasia, pj.fecha_constitucion,
       pj.representante_legal, pj.actividad_codigo
FROM persona p
LEFT JOIN persona_fisica  pf ON pf.persona = p.persona
LEFT JOIN persona_juridica pj ON pj.persona = p.persona;
