-- ============================================================================
-- V29 - Plantillas de contratos y pagares (REQ-0041)
-- Decision del usuario: sin JasperReports ni .jrxml. Los documentos se generan
-- como PDF con OpenPDF usando plantillas configurables y variables validadas.
-- ============================================================================

-- V28 fuerza RLS tambien al owner. Flyway necesita contexto SUPERADMIN para
-- sembrar pantalla y plantillas globales tenant=-1.
SELECT set_config('app.tenant', '-1', true);

ALTER TABLE permiso_usuario DROP CONSTRAINT IF EXISTS permiso_usuario_accion_check;
ALTER TABLE permiso_usuario ADD CONSTRAINT permiso_usuario_accion_check CHECK (accion IN
  ('OPERAR','VER','CREAR','EDITAR','INACTIVAR','REACTIVAR','EXPORTAR','VER_AUDITORIA',
   'GENERAR_CONTRATO','GENERAR_PAGARE','DESCARGAR_DOCUMENTO'));

ALTER TABLE permiso_grupo DROP CONSTRAINT IF EXISTS permiso_grupo_accion_check;
ALTER TABLE permiso_grupo ADD CONSTRAINT permiso_grupo_accion_check CHECK (accion IN
  ('OPERAR','VER','CREAR','EDITAR','INACTIVAR','REACTIVAR','EXPORTAR','VER_AUDITORIA',
   'GENERAR_CONTRATO','GENERAR_PAGARE','DESCARGAR_DOCUMENTO'));

CREATE TABLE plantilla_documento (
  plantilla_documento bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant              bigint NOT NULL REFERENCES persona_juridica(persona),
  codigo              varchar(60) NOT NULL,
  descripcion         varchar(180) NOT NULL,
  tipo                varchar(20) NOT NULL CHECK (tipo IN ('CONTRATO','PAGARE')),
  tipo_operacion      varchar(20),
  tipo_contrato       bigint REFERENCES entidad(entidad),
  version_plantilla   integer NOT NULL DEFAULT 1,
  formato_cuerpo      varchar(20) NOT NULL DEFAULT 'TEXTO' CHECK (formato_cuerpo IN ('TEXTO')),
  cuerpo              text NOT NULL,
  estado              varchar(10) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO')),
  usuario_creacion    varchar(20) NOT NULL,
  fecha_creacion      timestamptz NOT NULL,
  usuario_modificacion varchar(20),
  fecha_modificacion  timestamptz,
  version             bigint NOT NULL DEFAULT 0,
  UNIQUE (tenant, codigo)
);
CREATE INDEX ix_plantilla_documento_busqueda
  ON plantilla_documento (tenant, tipo, tipo_operacion, tipo_contrato, estado);

CREATE TABLE documento_generado (
  documento_generado  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant              bigint NOT NULL REFERENCES persona_juridica(persona),
  operacion           bigint NOT NULL REFERENCES operacion(operacion),
  cronograma_cuota    bigint REFERENCES cronograma_cuota(cronograma_cuota),
  tipo                varchar(20) NOT NULL CHECK (tipo IN ('CONTRATO','PAGARE')),
  plantilla_documento bigint NOT NULL REFERENCES plantilla_documento(plantilla_documento),
  version_plantilla   integer NOT NULL,
  nombre_archivo      varchar(180) NOT NULL,
  hash_contenido      varchar(64) NOT NULL,
  usuario_creacion    varchar(20) NOT NULL,
  fecha_creacion      timestamptz NOT NULL,
  usuario_modificacion varchar(20),
  fecha_modificacion  timestamptz,
  version             bigint NOT NULL DEFAULT 0
);
CREATE INDEX ix_documento_generado_operacion ON documento_generado (tenant, operacion, tipo);

INSERT INTO entidad (lista, codigo, tenant, descripcion, usuario_creacion, fecha_creacion)
VALUES ('PANTALLAS', 'plantillas-documentos', -1, 'Plantillas de documentos', 'sistema', now())
ON CONFLICT (lista, codigo, tenant) DO NOTHING;

INSERT INTO plantilla_documento
  (tenant, codigo, descripcion, tipo, tipo_operacion, tipo_contrato, version_plantilla,
   formato_cuerpo, cuerpo, estado, usuario_creacion, fecha_creacion)
VALUES
  (-1, 'CONTRATO_BASE', 'Contrato base de operacion', 'CONTRATO', NULL, NULL, 1, 'TEXTO',
$txt$
CONTRATO DE {{operacion.tipo}}

En fecha {{operacion.fecha_inicio}}, la empresa {{empresa.razon_social}} suscribe con {{cliente.nombre}}, documento {{cliente.documento}}, el presente contrato sobre el activo {{activo.descripcion}}, ubicado en {{activo.direccion}}.

Operacion Nro.: {{operacion.numero}}
Tipo de contrato: {{tipo_contrato.descripcion}}
Plazo: {{operacion.plazo}} meses
Fecha de inicio: {{operacion.fecha_inicio}}
Fecha de fin: {{operacion.fecha_fin}}
Monto total: Gs. {{operacion.monto_total}} ({{operacion.monto_total_letras}})

Las partes aceptan las condiciones registradas en el sistema SGInmo.

Firma empresa: ______________________________

Firma cliente: ______________________________
$txt$, 'ACTIVO', 'sistema', now()),
  (-1, 'PAGARE_BASE', 'Pagare base por cuota', 'PAGARE', NULL, NULL, 1, 'TEXTO',
$txt$
PAGARE A LA ORDEN

Por el presente pagare, {{deudor.nombre}}, documento {{deudor.documento}}, se obliga a pagar a {{acreedor.nombre}} la suma de Gs. {{cuota.monto}} ({{cuota.monto_letras}}), correspondiente a la cuota {{cuota.numero}} de la operacion {{operacion.numero}}.

Vencimiento: {{cuota.vencimiento}}

Firma deudor: ______________________________
$txt$, 'ACTIVO', 'sistema', now())
ON CONFLICT (tenant, codigo) DO NOTHING;

ALTER TABLE plantilla_documento ENABLE ROW LEVEL SECURITY;
ALTER TABLE plantilla_documento FORCE ROW LEVEL SECURITY;
CREATE POLICY p_plantilla_documento_sel ON plantilla_documento FOR SELECT
  USING (tenant = -1 OR tenant = app_tenant() OR app_tenant() = -1);
CREATE POLICY p_plantilla_documento_ins ON plantilla_documento FOR INSERT
  WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_plantilla_documento_upd ON plantilla_documento FOR UPDATE
  USING (app_tenant() = -1 OR tenant = app_tenant())
  WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_plantilla_documento_del ON plantilla_documento FOR DELETE
  USING (app_tenant() = -1 OR tenant = app_tenant());

ALTER TABLE documento_generado ENABLE ROW LEVEL SECURITY;
ALTER TABLE documento_generado FORCE ROW LEVEL SECURITY;
CREATE POLICY p_documento_generado_sel ON documento_generado FOR SELECT
  USING (tenant = app_tenant() OR app_tenant() = -1);
CREATE POLICY p_documento_generado_ins ON documento_generado FOR INSERT
  WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_documento_generado_upd ON documento_generado FOR UPDATE
  USING (app_tenant() = -1 OR tenant = app_tenant())
  WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_documento_generado_del ON documento_generado FOR DELETE
  USING (app_tenant() = -1 OR tenant = app_tenant());
