-- ============================================================================
-- V33 - Agenda operativa: recordatorios, tareas y vencimientos (REQ-0052)
-- Tabla de negocio 100% por-tenant. V28 no cubre tablas futuras, asi que la
-- tabla crea su propia RLS inline (patron documento_generado de V29).
-- ============================================================================

-- V28 fuerza RLS tambien al owner; Flyway necesita contexto SUPERADMIN para
-- registrar la pantalla global (tenant=-1) en 'entidad'.
SELECT set_config('app.tenant', '-1', true);

CREATE TABLE agenda_evento (
  agenda_evento   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant          bigint NOT NULL REFERENCES persona_juridica(persona),
  tipo            varchar(20) NOT NULL CHECK (tipo IN ('RECORDATORIO','TAREA','VENCIMIENTO','PROMESA')),
  titulo          varchar(180) NOT NULL,
  descripcion     varchar(500),
  fecha_evento    date NOT NULL,
  prioridad       varchar(10) NOT NULL DEFAULT 'MEDIA' CHECK (prioridad IN ('BAJA','MEDIA','ALTA')),
  responsable     varchar(20),
  estado          varchar(10) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE','EN_CURSO','RESUELTO','CERRADO')),
  -- Vinculo generico para eventos automaticos (dedup) y trazabilidad
  origen_tabla    varchar(30),
  origen_id       bigint,
  -- Vinculos de negocio opcionales (tareas manuales)
  operacion       bigint REFERENCES operacion(operacion),
  persona         bigint REFERENCES persona(persona),
  activo          bigint REFERENCES activo(activo),
  cobro           bigint REFERENCES cobro(cobro),
  usuario_creacion     varchar(20) NOT NULL,
  fecha_creacion       timestamptz NOT NULL,
  usuario_modificacion varchar(20),
  fecha_modificacion   timestamptz,
  version         bigint NOT NULL DEFAULT 0
);
CREATE INDEX ix_agenda_evento_lista ON agenda_evento (tenant, estado, fecha_evento);
-- Dedup de eventos automaticos: un solo evento por (tenant, tipo, origen). Las tareas
-- manuales tienen origen NULL y no entran al indice (parcial), asi no se limitan.
CREATE UNIQUE INDEX ux_agenda_evento_origen
  ON agenda_evento (tenant, tipo, origen_tabla, origen_id)
  WHERE origen_id IS NOT NULL;

-- Registro de la pantalla en el catalogo (perfil ADMINISTRADOR la ve sin sembrar permisos).
INSERT INTO entidad (lista, codigo, tenant, descripcion, usuario_creacion, fecha_creacion)
VALUES ('PANTALLAS', 'agenda', -1, 'Agenda y vencimientos', 'sistema', now())
ON CONFLICT (lista, codigo, tenant) DO NOTHING;

-- RLS inline (per-tenant, sin filas globales: patron documento_generado de V29).
ALTER TABLE agenda_evento ENABLE ROW LEVEL SECURITY;
ALTER TABLE agenda_evento FORCE ROW LEVEL SECURITY;
CREATE POLICY p_agenda_evento_sel ON agenda_evento FOR SELECT
  USING (tenant = app_tenant() OR app_tenant() = -1);
CREATE POLICY p_agenda_evento_ins ON agenda_evento FOR INSERT
  WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_agenda_evento_upd ON agenda_evento FOR UPDATE
  USING (app_tenant() = -1 OR tenant = app_tenant())
  WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_agenda_evento_del ON agenda_evento FOR DELETE
  USING (app_tenant() = -1 OR tenant = app_tenant());
