-- ============================================================================
-- V34 - Gestion documental: adjuntos por entidad de negocio (REQ-0053)
-- Tabla por-tenant. Los archivos fisicos viven FUERA del WAR (ruta configurable);
-- aqui solo se guardan metadatos + el nombre fisico (UUID, sin colisiones).
-- ============================================================================

SELECT set_config('app.tenant', '-1', true);

CREATE TABLE documento_adjunto (
  documento_adjunto  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant             bigint NOT NULL REFERENCES persona_juridica(persona),
  tipo               varchar(40) NOT NULL,
  descripcion        varchar(250),
  -- Vinculo a la entidad de negocio (generico)
  entidad_tipo       varchar(20) NOT NULL CHECK (entidad_tipo IN
                       ('PERSONA','ACTIVO','OPERACION','COBRO','LIQUIDACION','PLANTILLA','GENERAL')),
  entidad_id         bigint,
  -- Archivo fisico (fuera del WAR)
  nombre_original    varchar(255) NOT NULL,
  nombre_fisico      varchar(120) NOT NULL,
  content_type       varchar(120),
  tamano             bigint NOT NULL DEFAULT 0,
  fecha_vencimiento  date,
  estado             varchar(10) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO')),
  usuario_creacion     varchar(20) NOT NULL,
  fecha_creacion       timestamptz NOT NULL,
  usuario_modificacion varchar(20),
  fecha_modificacion   timestamptz,
  version            bigint NOT NULL DEFAULT 0,
  UNIQUE (tenant, nombre_fisico)
);
CREATE INDEX ix_documento_adjunto_entidad ON documento_adjunto (tenant, entidad_tipo, entidad_id, estado);

INSERT INTO entidad (lista, codigo, tenant, descripcion, usuario_creacion, fecha_creacion)
VALUES ('PANTALLAS', 'documentos', -1, 'Documentos y adjuntos', 'sistema', now())
ON CONFLICT (lista, codigo, tenant) DO NOTHING;

-- RLS inline per-tenant (patron documento_generado, V29).
ALTER TABLE documento_adjunto ENABLE ROW LEVEL SECURITY;
ALTER TABLE documento_adjunto FORCE ROW LEVEL SECURITY;
CREATE POLICY p_documento_adjunto_sel ON documento_adjunto FOR SELECT
  USING (tenant = app_tenant() OR app_tenant() = -1);
CREATE POLICY p_documento_adjunto_ins ON documento_adjunto FOR INSERT
  WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_documento_adjunto_upd ON documento_adjunto FOR UPDATE
  USING (app_tenant() = -1 OR tenant = app_tenant())
  WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_documento_adjunto_del ON documento_adjunto FOR DELETE
  USING (app_tenant() = -1 OR tenant = app_tenant());
