-- ============================================================================
-- V36 - Portal de cuenta para cliente/propietario (REQ-0055)
-- Perfil PORTAL (solo lectura, sin acceso administrativo), documentos visibles
-- en portal, y auditoria de accesos/descargas. Aislamiento por tenant (RLS) +
-- por persona (el portal solo consulta la persona vinculada al usuario logueado).
-- ============================================================================

SELECT set_config('app.tenant', '-1', true);

-- Nuevo perfil PORTAL (ademas de SUPERADMIN/ADMINISTRADOR/USUARIO).
ALTER TABLE usuario DROP CONSTRAINT IF EXISTS usuario_perfil_check;
ALTER TABLE usuario ADD CONSTRAINT usuario_perfil_check
  CHECK (perfil IN ('SUPERADMIN','ADMINISTRADOR','USUARIO','PORTAL'));

-- Un documento solo se muestra en el portal si esta explicitamente habilitado.
ALTER TABLE documento_adjunto ADD COLUMN IF NOT EXISTS visible_portal boolean NOT NULL DEFAULT false;

-- Auditoria de accesos y descargas del portal.
CREATE TABLE portal_acceso (
  portal_acceso  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant         bigint NOT NULL REFERENCES persona_juridica(persona),
  usuario_codigo varchar(20) NOT NULL,
  persona        bigint,
  accion         varchar(20) NOT NULL CHECK (accion IN ('ACCESO','DESCARGA')),
  recurso        varchar(160),
  ip             varchar(45),
  fecha          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_portal_acceso ON portal_acceso (tenant, persona, fecha);

ALTER TABLE portal_acceso ENABLE ROW LEVEL SECURITY;
ALTER TABLE portal_acceso FORCE ROW LEVEL SECURITY;
CREATE POLICY p_portal_acceso_sel ON portal_acceso FOR SELECT
  USING (tenant = app_tenant() OR app_tenant() = -1);
CREATE POLICY p_portal_acceso_ins ON portal_acceso FOR INSERT
  WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_portal_acceso_upd ON portal_acceso FOR UPDATE
  USING (app_tenant() = -1 OR tenant = app_tenant())
  WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_portal_acceso_del ON portal_acceso FOR DELETE
  USING (app_tenant() = -1 OR tenant = app_tenant());
