-- ============================================================================
-- V38 - Gestion de mora y cobranza (REQ-0057)
-- Cartera vencida = consulta sobre cronograma_cuota (misma fuente que cobros;
-- la mora en dinero usa la funcion existente f_mora_cuota, no se duplica calculo).
-- Este script agrega el registro de GESTIONES de cobranza y PROMESAS de pago.
-- La promesa NO es un pago ni cambia el estado de la cuota.
-- ============================================================================

SELECT set_config('app.tenant', '-1', true);

CREATE TABLE gestion_cobranza (
  gestion_cobranza  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant            bigint NOT NULL REFERENCES persona_juridica(persona),
  operacion         bigint REFERENCES operacion(operacion),
  cronograma_cuota  bigint REFERENCES cronograma_cuota(cronograma_cuota),
  cliente           bigint REFERENCES persona(persona),
  fecha             date NOT NULL,
  responsable       varchar(20),
  resultado         varchar(20) NOT NULL CHECK (resultado IN
                      ('CONTACTADO','NO_CONTACTADO','COMPROMISO','RECHAZO','ILOCALIZABLE','OTRO')),
  comentario        varchar(500),
  proxima_accion    varchar(250),
  proxima_fecha     date,
  usuario_creacion     varchar(20) NOT NULL,
  fecha_creacion       timestamptz NOT NULL,
  usuario_modificacion varchar(20),
  fecha_modificacion   timestamptz,
  version           bigint NOT NULL DEFAULT 0
);
CREATE INDEX ix_gestion_cobranza ON gestion_cobranza (tenant, operacion, fecha);

CREATE TABLE promesa_pago (
  promesa_pago      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant            bigint NOT NULL REFERENCES persona_juridica(persona),
  operacion         bigint REFERENCES operacion(operacion),
  cronograma_cuota  bigint REFERENCES cronograma_cuota(cronograma_cuota),
  cliente           bigint REFERENCES persona(persona),
  fecha_promesa     date NOT NULL,
  monto             numeric(15,2) NOT NULL,
  moneda            bigint REFERENCES moneda(moneda),
  estado            varchar(12) NOT NULL DEFAULT 'PENDIENTE'
                      CHECK (estado IN ('PENDIENTE','CUMPLIDA','INCUMPLIDA')),
  comentario        varchar(500),
  usuario_creacion     varchar(20) NOT NULL,
  fecha_creacion       timestamptz NOT NULL,
  usuario_modificacion varchar(20),
  fecha_modificacion   timestamptz,
  version           bigint NOT NULL DEFAULT 0
);
CREATE INDEX ix_promesa_pago ON promesa_pago (tenant, estado, fecha_promesa);

INSERT INTO entidad (lista, codigo, tenant, descripcion, usuario_creacion, fecha_creacion)
VALUES ('PANTALLAS', 'cobranza', -1, 'Mora y cobranza', 'sistema', now())
ON CONFLICT (lista, codigo, tenant) DO NOTHING;

-- RLS inline per-tenant (patron documento_generado, V29).
ALTER TABLE gestion_cobranza ENABLE ROW LEVEL SECURITY;
ALTER TABLE gestion_cobranza FORCE ROW LEVEL SECURITY;
CREATE POLICY p_gestion_cobranza_sel ON gestion_cobranza FOR SELECT USING (tenant = app_tenant() OR app_tenant() = -1);
CREATE POLICY p_gestion_cobranza_ins ON gestion_cobranza FOR INSERT WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_gestion_cobranza_upd ON gestion_cobranza FOR UPDATE USING (app_tenant() = -1 OR tenant = app_tenant()) WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_gestion_cobranza_del ON gestion_cobranza FOR DELETE USING (app_tenant() = -1 OR tenant = app_tenant());

ALTER TABLE promesa_pago ENABLE ROW LEVEL SECURITY;
ALTER TABLE promesa_pago FORCE ROW LEVEL SECURITY;
CREATE POLICY p_promesa_pago_sel ON promesa_pago FOR SELECT USING (tenant = app_tenant() OR app_tenant() = -1);
CREATE POLICY p_promesa_pago_ins ON promesa_pago FOR INSERT WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_promesa_pago_upd ON promesa_pago FOR UPDATE USING (app_tenant() = -1 OR tenant = app_tenant()) WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_promesa_pago_del ON promesa_pago FOR DELETE USING (app_tenant() = -1 OR tenant = app_tenant());
