-- ============================================================================
-- V42 - Importacion asistida CSV (REQ-0061): historial de importaciones.
-- Tabla por-tenant con RLS. El framework valida por fila y confirma atomico.
-- ============================================================================

SELECT set_config('app.tenant', '-1', true);

CREATE TABLE importacion (
  importacion     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant          bigint NOT NULL REFERENCES persona_juridica(persona),
  tipo            varchar(20) NOT NULL,
  archivo         varchar(180),
  usuario         varchar(20),
  filas_total     integer NOT NULL DEFAULT 0,
  filas_validas   integer NOT NULL DEFAULT 0,
  filas_error     integer NOT NULL DEFAULT 0,
  resultado       varchar(12) NOT NULL CHECK (resultado IN ('OK','FALLIDO')),
  detalle         varchar(2000),
  fecha           timestamptz NOT NULL DEFAULT now(),
  usuario_creacion varchar(20) NOT NULL DEFAULT 'sistema',
  fecha_creacion   timestamptz NOT NULL DEFAULT now(),
  version         bigint NOT NULL DEFAULT 0
);
CREATE INDEX ix_importacion ON importacion (tenant, tipo, fecha);

INSERT INTO entidad (lista, codigo, tenant, descripcion, usuario_creacion, fecha_creacion)
VALUES ('PANTALLAS', 'importacion', -1, 'Importacion de datos', 'sistema', now())
ON CONFLICT (lista, codigo, tenant) DO NOTHING;

ALTER TABLE importacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE importacion FORCE ROW LEVEL SECURITY;
CREATE POLICY p_importacion_sel ON importacion FOR SELECT USING (tenant = app_tenant() OR app_tenant() = -1);
CREATE POLICY p_importacion_ins ON importacion FOR INSERT WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_importacion_upd ON importacion FOR UPDATE USING (app_tenant() = -1 OR tenant = app_tenant()) WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_importacion_del ON importacion FOR DELETE USING (app_tenant() = -1 OR tenant = app_tenant());
