-- ============================================================================
-- V44 - Plantillas de roles/permisos por perfil operativo (REQ-0063)
-- Una plantilla es un set de (pantalla, accion) que se aplica a un grupo.
-- Aplicar solo escribe permiso_grupo (autorizacion real del backend); NUNCA
-- cambia el perfil del usuario (no concede SUPERADMIN por accidente).
-- ============================================================================

SELECT set_config('app.tenant', '-1', true);

CREATE TABLE rol_plantilla (
  rol_plantilla   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant          bigint NOT NULL REFERENCES persona_juridica(persona),
  codigo          varchar(30) NOT NULL,
  descripcion     varchar(120) NOT NULL,
  estado          varchar(10) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO')),
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz, version bigint NOT NULL DEFAULT 0,
  UNIQUE (tenant, codigo)
);
CREATE TABLE rol_plantilla_permiso (
  rol_plantilla_permiso bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rol_plantilla   bigint NOT NULL REFERENCES rol_plantilla(rol_plantilla) ON DELETE CASCADE,
  pantalla        varchar(60) NOT NULL,
  accion          varchar(30) NOT NULL,
  UNIQUE (rol_plantilla, pantalla, accion)
);

-- Plantillas base (globales, tenant=-1)
INSERT INTO rol_plantilla (tenant, codigo, descripcion, usuario_creacion, fecha_creacion)
  SELECT -1, v.cod, v.des, 'sistema', now() FROM (VALUES
    ('ADMINISTRADOR','Administrador operativo (todas las acciones)'),
    ('CAJA','Caja: cobros, comprobantes y arqueo'),
    ('COBRADOR','Cobranza y seguimiento de mora'),
    ('VENTAS','Ventas y alta de operaciones'),
    ('GERENCIA','Gerencia: tableros, reportes y auditoria'),
    ('AUDITOR','Auditor: solo lectura + auditoria'),
    ('CONSULTA','Solo consulta')
  ) AS v(cod, des)
  WHERE NOT EXISTS (SELECT 1 FROM rol_plantilla p WHERE p.tenant=-1 AND p.codigo=v.cod);

INSERT INTO rol_plantilla_permiso (rol_plantilla, pantalla, accion)
  SELECT rp.rol_plantilla, x.pantalla, x.accion
  FROM (VALUES
    ('ADMINISTRADOR','*','OPERAR'),
    ('CAJA','caja','VER'), ('CAJA','caja','OPERAR'), ('CAJA','comprobantes','VER'),
    ('CAJA','comprobantes','EXPORTAR'), ('CAJA','arqueo','VER'), ('CAJA','arqueo','EXPORTAR'),
    ('COBRADOR','cobranza','VER'), ('COBRADOR','cobranza','EDITAR'), ('COBRADOR','cobranza','EXPORTAR'),
    ('COBRADOR','caja','VER'), ('COBRADOR','personas','VER'), ('COBRADOR','operaciones','VER'),
    ('VENTAS','operaciones','VER'), ('VENTAS','operaciones','CREAR'), ('VENTAS','operaciones','EDITAR'),
    ('VENTAS','activos','VER'), ('VENTAS','personas','VER'), ('VENTAS','personas','CREAR'),
    ('VENTAS','agenda','VER'), ('VENTAS','agenda','CREAR'),
    ('GERENCIA','dashboard-gerencial','VER'), ('GERENCIA','reportes','VER'), ('GERENCIA','reportes','EXPORTAR'),
    ('GERENCIA','*','VER'), ('GERENCIA','*','VER_AUDITORIA'),
    ('AUDITOR','*','VER'), ('AUDITOR','*','VER_AUDITORIA'),
    ('CONSULTA','*','VER')
  ) AS x(cod, pantalla, accion)
  JOIN rol_plantilla rp ON rp.tenant=-1 AND rp.codigo=x.cod
  WHERE NOT EXISTS (SELECT 1 FROM rol_plantilla_permiso pp
                    WHERE pp.rol_plantilla=rp.rol_plantilla AND pp.pantalla=x.pantalla AND pp.accion=x.accion);

INSERT INTO entidad (lista, codigo, tenant, descripcion, usuario_creacion, fecha_creacion)
VALUES ('PANTALLAS', 'roles-plantilla', -1, 'Plantillas de roles', 'sistema', now())
ON CONFLICT (lista, codigo, tenant) DO NOTHING;

-- RLS en rol_plantilla (permite ver las globales -1 y las propias). El detalle se accede via join.
ALTER TABLE rol_plantilla ENABLE ROW LEVEL SECURITY;
ALTER TABLE rol_plantilla FORCE ROW LEVEL SECURITY;
CREATE POLICY p_rol_plantilla_sel ON rol_plantilla FOR SELECT USING (tenant = -1 OR tenant = app_tenant() OR app_tenant() = -1);
CREATE POLICY p_rol_plantilla_ins ON rol_plantilla FOR INSERT WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_rol_plantilla_upd ON rol_plantilla FOR UPDATE USING (app_tenant() = -1 OR tenant = app_tenant()) WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_rol_plantilla_del ON rol_plantilla FOR DELETE USING (app_tenant() = -1 OR tenant = app_tenant());
