-- ============================================================================
-- V45 - Politicas de seguridad (REQ-0064): parametros configurables, auditoria
-- de login e historial de contrasenas. Estas tablas de seguridad NO llevan RLS
-- (consistente con usuario/permiso_grupo, excluidas de V28); son admin-only.
-- ============================================================================

SELECT set_config('app.tenant', '-1', true);

-- Parametros de politica (globales; el login/cambio de clave ya los lee via el SPI).
INSERT INTO parametro_sistema (tenant, clave, valor, descripcion, tipo, grupo, valor_defecto, usuario_creacion, fecha_creacion)
  SELECT -1, v.clave, v.valor, v.descripcion, v.tipo, 'Seguridad', v.valor, 'sistema', now()
  FROM (VALUES
    ('LOGIN_MAX_INTENTOS',      '5',  'Intentos fallidos antes de bloquear', 'ENTERO'),
    ('LOGIN_BLOQUEO_MINUTOS',   '15', 'Minutos de bloqueo por intentos',     'ENTERO'),
    ('LOGIN_PASS_MIN_LEN',      '8',  'Longitud minima de contrasena',       'ENTERO'),
    ('LOGIN_PASS_COMPLEJIDAD',  'NO', 'Exigir letra + numero en la contrasena', 'STRING'),
    ('LOGIN_SESION_TIMEOUT_MIN','30', 'Timeout de sesion (minutos)',         'ENTERO'),
    ('LOGIN_PASS_HISTORIAL',    '3',  'Cantidad de contrasenas previas a no reutilizar', 'ENTERO')
  ) AS v(clave, valor, descripcion, tipo)
  WHERE NOT EXISTS (SELECT 1 FROM parametro_sistema p WHERE p.clave=v.clave AND p.tenant=-1);

-- Auditoria de accesos (login exito/fallo). Sin tenant: el login es previo al contexto de empresa.
CREATE TABLE login_evento (
  login_evento   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_codigo varchar(30),
  exito          boolean NOT NULL,
  causa          varchar(40),
  ip             varchar(45),
  fecha          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_login_evento ON login_evento (fecha DESC);

-- Historial de contrasenas para evitar reutilizacion (hash bcrypt; nunca texto).
CREATE TABLE password_historial (
  password_historial bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario        bigint NOT NULL,
  password_hash  varchar(100) NOT NULL,
  fecha          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_password_historial ON password_historial (usuario, fecha DESC);

INSERT INTO entidad (lista, codigo, tenant, descripcion, usuario_creacion, fecha_creacion)
VALUES ('PANTALLAS', 'seguridad', -1, 'Politicas de seguridad', 'sistema', now())
ON CONFLICT (lista, codigo, tenant) DO NOTHING;
