-- ============================================================================
-- V46 - Auditoria funcional visible (REQ-0067): historial de cambios de registros
-- sensibles (quien, que, valor anterior/nuevo, cuando, modulo, motivo). Es de
-- NEGOCIO y lleva tenant + RLS (nunca se ven cambios de otra empresa). Complementa
-- -no reemplaza- los sellos tecnicos usuario_creacion/fecha_* de cada entidad.
-- La escritura la hace AuditoriaFuncionalService (nunca guarda hashes/tokens).
-- ============================================================================

SELECT set_config('app.tenant', '-1', true);

CREATE TABLE auditoria_funcional (
  auditoria_funcional bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant          bigint NOT NULL,
  entidad         varchar(60)  NOT NULL,   -- nombre logico del maestro sensible (persona, articulo, ...)
  registro_id     varchar(60),             -- id/codigo del registro afectado (texto para soportar claves variadas)
  accion          varchar(20)  NOT NULL,   -- CREAR | EDITAR | INACTIVAR | REACTIVAR | ANULAR | COBRAR | DESCUENTO | LIQUIDAR | REGENERAR | DESBLOQUEAR | OTRO
  campo           varchar(60),             -- campo modificado (null para altas/acciones sin diff de campo)
  valor_anterior  text,                    -- valor previo (null en alta); nunca secretos
  valor_nuevo     text,                    -- valor nuevo (null en inactivacion sin cambio de campo)
  modulo          varchar(60),             -- pantalla/modulo de origen
  motivo          varchar(300),            -- motivo (obligatorio en inactivacion de maestros sensibles)
  usuario_codigo  varchar(30)  NOT NULL,   -- quien hizo el cambio
  fecha           timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT ck_auditoria_funcional_accion CHECK (accion IN
    ('CREAR','EDITAR','INACTIVAR','REACTIVAR','ANULAR','COBRAR','DESCUENTO','LIQUIDAR','REGENERAR','DESBLOQUEAR','OTRO'))
);
CREATE INDEX ix_auditoria_funcional_reg   ON auditoria_funcional (tenant, entidad, registro_id, fecha DESC);
CREATE INDEX ix_auditoria_funcional_fecha ON auditoria_funcional (tenant, fecha DESC);
CREATE INDEX ix_auditoria_funcional_user  ON auditoria_funcional (tenant, usuario_codigo, fecha DESC);

-- RLS multiempresa (mismo patron que las tablas de negocio; ver V28).
ALTER TABLE auditoria_funcional ENABLE ROW LEVEL SECURITY;
ALTER TABLE auditoria_funcional FORCE ROW LEVEL SECURITY;
CREATE POLICY p_auditoria_funcional_sel ON auditoria_funcional FOR SELECT
  USING (tenant = app_tenant() OR app_tenant() = -1);
CREATE POLICY p_auditoria_funcional_ins ON auditoria_funcional FOR INSERT
  WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
-- La auditoria es inmutable: sin policies de UPDATE/DELETE (nadie puede alterarla ni borrarla,
-- ni siquiera el SUPERADMIN, salvo por mantenimiento fuera de la app).

-- Pantalla de consulta (permiso separado para ver auditoria).
INSERT INTO entidad (lista, codigo, tenant, descripcion, usuario_creacion, fecha_creacion)
VALUES ('PANTALLAS', 'auditoria', -1, 'Auditoria funcional', 'sistema', now())
ON CONFLICT (lista, codigo, tenant) DO NOTHING;
