-- ============================================================================
-- V50 - Objetivos gerenciales tipo BSC/BCM (REQ-0073): metas configurables con
-- calculo automatico, semaforo y brecha. De NEGOCIO -> tenant + RLS (V28). El historial
-- de mediciones (objetivo_medicion) conserva la evolucion; los objetivos no se borran
-- (baja logica). El calculo del valor actual lo hace ObjetivoService (centralizado).
-- ============================================================================

SELECT set_config('app.tenant', '-1', true);

CREATE TABLE objetivo_gerencial (
  objetivo_gerencial bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant          bigint NOT NULL,
  indicador       varchar(30)  NOT NULL,   -- ocupacion|cobro_mensual|mora_maxima|rentabilidad_minima|contratos_nuevos|egresos_maximos|vacancia_maxima
  descripcion     varchar(200) NOT NULL,
  meta            numeric(16,2) NOT NULL,
  unidad          varchar(12)  NOT NULL,   -- PORCENTAJE | MONTO | CANTIDAD
  sentido         varchar(8)   NOT NULL,   -- MINIMO (llegar a) | MAXIMO (no superar)
  periodo         varchar(14)  NOT NULL DEFAULT 'MENSUAL',  -- MENSUAL|TRIMESTRAL|ANUAL|PERSONALIZADO
  alcance         varchar(16)  NOT NULL DEFAULT 'EMPRESA',  -- EMPRESA|SUCURSAL|TIPO_ACTIVO|ZONA|PROPIETARIO|RESPONSABLE
  alcance_ref     bigint,                  -- id del alcance (sucursal/tipo/...); null = toda la empresa
  moneda          bigint,                  -- requerido para unidad MONTO (no mezcla monedas)
  umbral_adv      numeric(16,2),           -- umbral de advertencia (amarillo); null = derivado
  vigencia_desde  date NOT NULL DEFAULT current_date,
  vigencia_hasta  date,
  estado          varchar(10)  NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO')),
  version         bigint NOT NULL DEFAULT 0,
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL DEFAULT now(),
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  CONSTRAINT ck_obj_indicador CHECK (indicador IN
    ('ocupacion','cobro_mensual','mora_maxima','rentabilidad_minima','contratos_nuevos','egresos_maximos','vacancia_maxima')),
  CONSTRAINT ck_obj_unidad CHECK (unidad IN ('PORCENTAJE','MONTO','CANTIDAD')),
  CONSTRAINT ck_obj_sentido CHECK (sentido IN ('MINIMO','MAXIMO')),
  CONSTRAINT ck_obj_meta_pct CHECK (unidad <> 'PORCENTAJE' OR (meta >= 0 AND meta <= 100))
);
CREATE INDEX ix_objetivo_tenant ON objetivo_gerencial (tenant, estado);

CREATE TABLE objetivo_medicion (
  objetivo_medicion bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant          bigint NOT NULL,
  objetivo        bigint NOT NULL REFERENCES objetivo_gerencial(objetivo_gerencial),
  periodo_desde   date NOT NULL,
  periodo_hasta   date NOT NULL,
  valor           numeric(16,2) NOT NULL,
  cumplimiento_pct numeric(6,2),
  semaforo        varchar(10) NOT NULL,    -- OK | ADVERTENCIA | CRITICO
  fecha           timestamptz NOT NULL DEFAULT now(),
  usuario_creacion varchar(20) NOT NULL DEFAULT 'sistema'
);
CREATE INDEX ix_objetivo_medicion ON objetivo_medicion (tenant, objetivo, fecha DESC);

-- RLS multiempresa (patron V28).
ALTER TABLE objetivo_gerencial ENABLE ROW LEVEL SECURITY;
ALTER TABLE objetivo_gerencial FORCE ROW LEVEL SECURITY;
CREATE POLICY p_objetivo_sel ON objetivo_gerencial FOR SELECT USING (tenant = app_tenant() OR app_tenant() = -1);
CREATE POLICY p_objetivo_ins ON objetivo_gerencial FOR INSERT WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_objetivo_upd ON objetivo_gerencial FOR UPDATE USING (app_tenant() = -1 OR tenant = app_tenant()) WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());

ALTER TABLE objetivo_medicion ENABLE ROW LEVEL SECURITY;
ALTER TABLE objetivo_medicion FORCE ROW LEVEL SECURITY;
CREATE POLICY p_objmed_sel ON objetivo_medicion FOR SELECT USING (tenant = app_tenant() OR app_tenant() = -1);
CREATE POLICY p_objmed_ins ON objetivo_medicion FOR INSERT WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());

INSERT INTO entidad (lista, codigo, tenant, descripcion, usuario_creacion, fecha_creacion)
VALUES ('PANTALLAS', 'objetivos', -1, 'Objetivos gerenciales', 'sistema', now())
ON CONFLICT (lista, codigo, tenant) DO NOTHING;
