-- ============================================================================
-- V51 - Alertas gerenciales (REQ-0075): desviaciones/brechas accionables derivadas de
-- los objetivos (REQ-0073) y reglas configurables. De NEGOCIO -> tenant + RLS (V28). Dedup
-- por (tenant, hash_dedup) mientras la alerta esta ABIERTA. Se pueden marcar revisadas/
-- descartadas con motivo y usuario (historial). Preparada para envio futuro (sin exigirlo).
-- ============================================================================

SELECT set_config('app.tenant', '-1', true);

-- Dias de aviso para contratos por vencer (configurable).
INSERT INTO parametro_sistema (tenant, clave, valor, descripcion, tipo, grupo, valor_defecto, usuario_creacion, fecha_creacion)
  SELECT -1, 'CONTRATOS_AVISO_DIAS', '30', 'Dias de anticipacion para avisar contratos por vencer', 'ENTERO', 'Gerencia', '30', 'sistema', now()
  WHERE NOT EXISTS (SELECT 1 FROM parametro_sistema p WHERE p.clave='CONTRATOS_AVISO_DIAS' AND p.tenant=-1);

CREATE TABLE alerta_gerencial (
  alerta_gerencial bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant          bigint NOT NULL,
  tipo            varchar(30)  NOT NULL,   -- OBJETIVO | RENTABILIDAD | CONTRATOS | COBROS | MORA | OCUPACION ...
  indicador       varchar(40),
  prioridad       varchar(12)  NOT NULL,   -- CRITICA | ALTA | MEDIA | INFORMATIVA
  causa           varchar(300) NOT NULL,
  impacto         varchar(300),
  accion_sugerida varchar(300),
  drill_clave     varchar(40),             -- clave de evidencia (REQ-0074)
  drill_ref       bigint,
  hash_dedup      varchar(120) NOT NULL,   -- tipo|indicador|periodo -> evita duplicar
  estado          varchar(12)  NOT NULL DEFAULT 'ABIERTA' CHECK (estado IN ('ABIERTA','REVISADA','DESCARTADA')),
  motivo_cierre   varchar(300),
  usuario_cierre  varchar(20),
  fecha_cierre    timestamptz,
  fecha           timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ck_alerta_prioridad CHECK (prioridad IN ('CRITICA','ALTA','MEDIA','INFORMATIVA'))
);
CREATE INDEX ix_alerta_tenant ON alerta_gerencial (tenant, estado, prioridad);
-- Dedup: como maximo una alerta ABIERTA por (tenant, hash_dedup).
CREATE UNIQUE INDEX ux_alerta_abierta ON alerta_gerencial (tenant, hash_dedup) WHERE estado='ABIERTA';

ALTER TABLE alerta_gerencial ENABLE ROW LEVEL SECURITY;
ALTER TABLE alerta_gerencial FORCE ROW LEVEL SECURITY;
CREATE POLICY p_alerta_sel ON alerta_gerencial FOR SELECT USING (tenant = app_tenant() OR app_tenant() = -1);
CREATE POLICY p_alerta_ins ON alerta_gerencial FOR INSERT WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_alerta_upd ON alerta_gerencial FOR UPDATE USING (app_tenant() = -1 OR tenant = app_tenant()) WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());

INSERT INTO entidad (lista, codigo, tenant, descripcion, usuario_creacion, fecha_creacion)
VALUES ('PANTALLAS', 'alertas', -1, 'Alertas gerenciales', 'sistema', now())
ON CONFLICT (lista, codigo, tenant) DO NOTHING;
