-- ============================================================================
-- V52 - Portal externo de socios (REQ-0078): identidad externa por CI/RUC + OTP +
-- password propio de la persona, SEPARADA del usuario administrativo interno.
-- Reemplaza el mecanismo de acceso del REQ-0055 (usuario.perfil='PORTAL').
--
-- Credenciales y OTP viven por (tenant, persona), NUNCA en texto plano (bcrypt).
-- De NEGOCIO -> tenant + RLS (V28). La auditoria (portal_acceso, V36) se amplia con
-- nuevos eventos de seguridad y user-agent.
-- ============================================================================

SELECT set_config('app.tenant', '-1', true);

-- ── Parametros configurables (defaults globales -1; se pueden sobre-escribir por empresa) ──
INSERT INTO parametro_sistema (tenant, clave, valor, descripcion, tipo, grupo, valor_defecto, usuario_creacion, fecha_creacion)
  SELECT -1, 'PORTAL_OTP_EXPIRA_MIN', '10', 'Minutos de validez del codigo OTP del portal', 'ENTERO', 'Portal', '10', 'sistema', now()
  WHERE NOT EXISTS (SELECT 1 FROM parametro_sistema p WHERE p.clave='PORTAL_OTP_EXPIRA_MIN' AND p.tenant=-1);
INSERT INTO parametro_sistema (tenant, clave, valor, descripcion, tipo, grupo, valor_defecto, usuario_creacion, fecha_creacion)
  SELECT -1, 'PORTAL_OTP_LARGO', '6', 'Cantidad de digitos del codigo OTP del portal', 'ENTERO', 'Portal', '6', 'sistema', now()
  WHERE NOT EXISTS (SELECT 1 FROM parametro_sistema p WHERE p.clave='PORTAL_OTP_LARGO' AND p.tenant=-1);
INSERT INTO parametro_sistema (tenant, clave, valor, descripcion, tipo, grupo, valor_defecto, usuario_creacion, fecha_creacion)
  SELECT -1, 'PORTAL_OTP_MAX_INTENTOS', '5', 'Intentos de validacion permitidos por OTP antes de invalidarlo', 'ENTERO', 'Portal', '5', 'sistema', now()
  WHERE NOT EXISTS (SELECT 1 FROM parametro_sistema p WHERE p.clave='PORTAL_OTP_MAX_INTENTOS' AND p.tenant=-1);
INSERT INTO parametro_sistema (tenant, clave, valor, descripcion, tipo, grupo, valor_defecto, usuario_creacion, fecha_creacion)
  SELECT -1, 'PORTAL_LOGIN_MAX_INTENTOS', '5', 'Intentos de login con password antes del bloqueo temporal', 'ENTERO', 'Portal', '5', 'sistema', now()
  WHERE NOT EXISTS (SELECT 1 FROM parametro_sistema p WHERE p.clave='PORTAL_LOGIN_MAX_INTENTOS' AND p.tenant=-1);
INSERT INTO parametro_sistema (tenant, clave, valor, descripcion, tipo, grupo, valor_defecto, usuario_creacion, fecha_creacion)
  SELECT -1, 'PORTAL_BLOQUEO_MIN', '15', 'Minutos de bloqueo temporal tras exceder intentos de login/OTP', 'ENTERO', 'Portal', '15', 'sistema', now()
  WHERE NOT EXISTS (SELECT 1 FROM parametro_sistema p WHERE p.clave='PORTAL_BLOQUEO_MIN' AND p.tenant=-1);

-- ── Credencial de portal por persona+tenant (identidad externa) ──
CREATE TABLE persona_portal_credencial (
  persona_portal_credencial bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant            bigint      NOT NULL REFERENCES persona_juridica(persona),
  persona           bigint      NOT NULL REFERENCES persona(persona),
  password_hash     varchar(100),                          -- bcrypt; NULL hasta el primer set
  ultimo_cambio     timestamptz,
  estado            varchar(10) NOT NULL DEFAULT 'ACTIVO',  -- ACTIVO | BLOQUEADO
  intentos_fallidos int         NOT NULL DEFAULT 0,
  bloqueado_hasta   timestamptz,
  fecha_creacion    timestamptz NOT NULL DEFAULT now(),
  version           bigint      NOT NULL DEFAULT 0,
  CONSTRAINT ux_portal_cred UNIQUE (tenant, persona),
  CONSTRAINT ck_portal_cred_estado CHECK (estado IN ('ACTIVO','BLOQUEADO'))
);
ALTER TABLE persona_portal_credencial ENABLE ROW LEVEL SECURITY;
ALTER TABLE persona_portal_credencial FORCE ROW LEVEL SECURITY;
CREATE POLICY p_portal_cred_sel ON persona_portal_credencial FOR SELECT USING (tenant = app_tenant() OR app_tenant() = -1);
CREATE POLICY p_portal_cred_ins ON persona_portal_credencial FOR INSERT WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_portal_cred_upd ON persona_portal_credencial FOR UPDATE USING (app_tenant() = -1 OR tenant = app_tenant()) WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());

-- ── OTP de portal (codigo hasheado, uso unico, expiracion, intentos) ──
CREATE TABLE portal_otp (
  portal_otp     bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant         bigint      NOT NULL REFERENCES persona_juridica(persona),
  persona        bigint      NOT NULL REFERENCES persona(persona),
  codigo_hash    varchar(100) NOT NULL,                    -- bcrypt del codigo; nunca plano
  proposito      varchar(20)  NOT NULL DEFAULT 'LOGIN',    -- LOGIN | RECUPERACION
  canal          varchar(10),                              -- EMAIL | SMS
  expira_en      timestamptz NOT NULL,
  intentos       int         NOT NULL DEFAULT 0,
  usado          boolean     NOT NULL DEFAULT false,
  creado_en      timestamptz NOT NULL DEFAULT now(),
  version        bigint      NOT NULL DEFAULT 0,
  CONSTRAINT ck_portal_otp_prop CHECK (proposito IN ('LOGIN','RECUPERACION'))
);
CREATE INDEX ix_portal_otp ON portal_otp (tenant, persona, usado, creado_en);
ALTER TABLE portal_otp ENABLE ROW LEVEL SECURITY;
ALTER TABLE portal_otp FORCE ROW LEVEL SECURITY;
CREATE POLICY p_portal_otp_sel ON portal_otp FOR SELECT USING (tenant = app_tenant() OR app_tenant() = -1);
CREATE POLICY p_portal_otp_ins ON portal_otp FOR INSERT WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_portal_otp_upd ON portal_otp FOR UPDATE USING (app_tenant() = -1 OR tenant = app_tenant()) WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());

-- ── Auditoria (V36 portal_acceso): ampliar acciones y agregar user-agent ──
ALTER TABLE portal_acceso DROP CONSTRAINT IF EXISTS portal_acceso_accion_check;
ALTER TABLE portal_acceso ADD CONSTRAINT ck_portal_acceso_accion
  CHECK (accion IN ('ACCESO','DESCARGA','SOLICITUD_OTP','VALIDACION_OTP','OTP_FALLIDO',
                    'LOGIN','LOGIN_FALLIDO','CAMBIO_PASSWORD','LOGOUT'));
ALTER TABLE portal_acceso ADD COLUMN IF NOT EXISTS user_agent varchar(250);
-- usuario_codigo pasa a admitir el marcador externo 'portal' (ya lo usa el REQ-0055).
