-- ============================================================================
-- V56 - Portal: informar transferencia + adjuntar comprobante + bandeja + aplicacion (REQ-0083 Fase 1).
-- El socio informa una transferencia y adjunta el comprobante; queda en bandeja operativa interna donde
-- un usuario la revisa y, si es valida, aplica el pago reutilizando el motor de cobros (forma TRANSFERENCIA).
-- Sin OCR ni conciliacion bancaria (columnas reservadas nullable para las fases 2/3). RLS por tenant.
-- ============================================================================

SELECT set_config('app.tenant', '-1', true);

-- Parametros (defaults globales; override por empresa).
INSERT INTO parametro_sistema (tenant, clave, valor, descripcion, tipo, grupo, valor_defecto, usuario_creacion, fecha_creacion)
  SELECT -1, 'PORTAL_TRANSF_TAMANO_MAX_MB', '8', 'Tamano maximo del comprobante de transferencia (MB)', 'ENTERO', 'Portal', '8', 'sistema', now()
  WHERE NOT EXISTS (SELECT 1 FROM parametro_sistema p WHERE p.clave='PORTAL_TRANSF_TAMANO_MAX_MB' AND p.tenant=-1);
INSERT INTO parametro_sistema (tenant, clave, valor, descripcion, tipo, grupo, valor_defecto, usuario_creacion, fecha_creacion)
  SELECT -1, 'PORTAL_TRANSF_CUENTAS', '', 'Cuentas receptoras a mostrar al socio (texto informativo)', 'STRING', 'Portal', '', 'sistema', now()
  WHERE NOT EXISTS (SELECT 1 FROM parametro_sistema p WHERE p.clave='PORTAL_TRANSF_CUENTAS' AND p.tenant=-1);

CREATE TABLE portal_pago_transferencia (
  portal_pago_transferencia bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant              bigint       NOT NULL REFERENCES persona_juridica(persona),
  persona             bigint       NOT NULL REFERENCES persona(persona),
  estado              varchar(15)  NOT NULL DEFAULT 'RECIBIDO'
                        CHECK (estado IN ('RECIBIDO','EN_REVISION','OBSERVADO','RECHAZADO','APLICADO')),
  importe             numeric(15,2) NOT NULL,
  moneda              bigint,
  fecha_transferencia date,
  banco_origen        varchar(80),
  cuenta_origen       varchar(40),
  cuenta_destino      varchar(40),
  numero_transaccion  varchar(60),
  observacion_cliente varchar(300),
  documento           bigint,                 -- documento/cuota a imputar (null = a definir en bandeja)
  motivo_revision     varchar(300),           -- motivo de observacion/rechazo (visible para el socio)
  cobro               bigint,                 -- cobro generado al APLICAR
  usuario_revision    varchar(20),
  fecha_revision      timestamptz,
  -- comprobante (un archivo por transferencia en Fase 1; almacenamiento controlado fuera del webroot)
  archivo_nombre      varchar(255),
  archivo_fisico      varchar(120),
  archivo_mime        varchar(120),
  archivo_hash        varchar(64),
  archivo_tamano      bigint,
  fecha               timestamptz  NOT NULL DEFAULT now(),
  -- reservadas para Fase 2 (OCR) / Fase 3 (conciliacion): nullable, no usadas en Fase 1
  texto_ocr           text,
  confianza_ocr       numeric(5,2),
  movimiento_bancario bigint,
  version             bigint       NOT NULL DEFAULT 0
);
CREATE INDEX ix_ppt_persona ON portal_pago_transferencia (tenant, persona, estado);
CREATE INDEX ix_ppt_estado  ON portal_pago_transferencia (tenant, estado, fecha);
-- Anti-doble-aplicacion: un mismo numero_transaccion no puede quedar APLICADO dos veces.
CREATE UNIQUE INDEX ux_ppt_aplicada ON portal_pago_transferencia (tenant, numero_transaccion)
  WHERE estado='APLICADO' AND numero_transaccion IS NOT NULL;

ALTER TABLE portal_pago_transferencia ENABLE ROW LEVEL SECURITY;
ALTER TABLE portal_pago_transferencia FORCE ROW LEVEL SECURITY;
CREATE POLICY p_ppt_sel ON portal_pago_transferencia FOR SELECT USING (tenant = app_tenant() OR app_tenant() = -1);
CREATE POLICY p_ppt_ins ON portal_pago_transferencia FOR INSERT WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_ppt_upd ON portal_pago_transferencia FOR UPDATE USING (app_tenant() = -1 OR tenant = app_tenant()) WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());

-- Pantalla interna de la bandeja operativa.
INSERT INTO entidad (lista, codigo, tenant, descripcion, usuario_creacion, fecha_creacion)
VALUES ('PANTALLAS', 'transferencias', -1, 'Transferencias informadas (bandeja)', 'sistema', now())
ON CONFLICT (lista, codigo, tenant) DO NOTHING;
