-- ============================================================================
-- V58 - Conciliacion bancaria (REQ-0085 Fase 3): movimientos bancarios importados + cruce con las
-- transferencias informadas + aplicacion. Fuente: carga manual + importacion de archivo (sin credenciales
-- del banco; IMAP/API queda como extension). RLS por tenant; idempotencia por hash externo.
-- ============================================================================

SELECT set_config('app.tenant', '-1', true);

-- Parametros de conciliacion/autoaplicacion (defaults globales).
INSERT INTO parametro_sistema (tenant, clave, valor, descripcion, tipo, grupo, valor_defecto, usuario_creacion, fecha_creacion)
  SELECT -1, 'PORTAL_TRANSF_TOLERANCIA_DIAS', '2', 'Tolerancia de dias entre comprobante y movimiento bancario para cruzar', 'ENTERO', 'Portal', '2', 'sistema', now()
  WHERE NOT EXISTS (SELECT 1 FROM parametro_sistema p WHERE p.clave='PORTAL_TRANSF_TOLERANCIA_DIAS' AND p.tenant=-1);
INSERT INTO parametro_sistema (tenant, clave, valor, descripcion, tipo, grupo, valor_defecto, usuario_creacion, fecha_creacion)
  SELECT -1, 'PORTAL_TRANSF_MONTO_MAX_AUTO', '0', 'Monto maximo autoaplicable de transferencia (0 = no autoaplicar)', 'DECIMAL', 'Portal', '0', 'sistema', now()
  WHERE NOT EXISTS (SELECT 1 FROM parametro_sistema p WHERE p.clave='PORTAL_TRANSF_MONTO_MAX_AUTO' AND p.tenant=-1);

CREATE TABLE movimiento_bancario_importado (
  movimiento_bancario_importado bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant              bigint       NOT NULL REFERENCES persona_juridica(persona),
  fuente              varchar(20)  NOT NULL DEFAULT 'MANUAL' CHECK (fuente IN ('MANUAL','ARCHIVO','IMAP')),
  banco               varchar(80),
  cuenta              varchar(40),
  fecha               date,
  importe             numeric(15,2) NOT NULL,
  moneda              bigint,
  referencia          varchar(80),
  remitente           varchar(120),
  estado_conciliacion varchar(15)  NOT NULL DEFAULT 'PENDIENTE'
                        CHECK (estado_conciliacion IN ('PENDIENTE','CONCILIADO','DESCARTADO')),
  hash_externo        varchar(120),
  transferencia       bigint,      -- transferencia con la que se concilio
  usuario_carga       varchar(20),
  fecha_importacion   timestamptz  NOT NULL DEFAULT now(),
  version             bigint       NOT NULL DEFAULT 0
);
CREATE INDEX ix_mbi_estado ON movimiento_bancario_importado (tenant, estado_conciliacion, fecha);
-- Idempotencia: un mismo aviso (hash externo) no se importa dos veces.
CREATE UNIQUE INDEX ux_mbi_hash ON movimiento_bancario_importado (tenant, hash_externo) WHERE hash_externo IS NOT NULL;

ALTER TABLE movimiento_bancario_importado ENABLE ROW LEVEL SECURITY;
ALTER TABLE movimiento_bancario_importado FORCE ROW LEVEL SECURITY;
CREATE POLICY p_mbi_sel ON movimiento_bancario_importado FOR SELECT USING (tenant = app_tenant() OR app_tenant() = -1);
CREATE POLICY p_mbi_ins ON movimiento_bancario_importado FOR INSERT WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_mbi_upd ON movimiento_bancario_importado FOR UPDATE USING (app_tenant() = -1 OR tenant = app_tenant()) WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
