-- ============================================================================
-- V60 - Portal: intenciones de pago por QR dinamico (REQ-0094 Fase 2, base).
-- Cada QR dinamico persiste una "intencion de pago" con una referencia UNICA. Cuando se importa un
-- movimiento bancario (REQ-0085) cuya referencia coincide y el importe cuadra, la intencion se marca
-- CONCILIADA y queda linkeada al movimiento, lista para que el operador aplique el cobro.
-- La aplicacion 100% automatica y el webhook del banco/PSP quedan para cuando exista el convenio.
-- ============================================================================

SELECT set_config('app.tenant', '-1', true);

INSERT INTO parametro_sistema (tenant, clave, valor, descripcion, tipo, grupo, valor_defecto, usuario_creacion, fecha_creacion)
  SELECT -1, 'PORTAL_QR_INTENTO_EXPIRA_MIN', '1440', 'Minutos de validez de un QR de pago dinamico (intencion)', 'ENTERO', 'Portal QR', '1440', 'sistema', now()
  WHERE NOT EXISTS (SELECT 1 FROM parametro_sistema p WHERE p.clave='PORTAL_QR_INTENTO_EXPIRA_MIN' AND p.tenant=-1);

CREATE TABLE portal_pago_qr (
  portal_pago_qr  bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant          bigint       NOT NULL REFERENCES persona_juridica(persona),
  persona         bigint       NOT NULL REFERENCES persona,
  referencia      varchar(30)  NOT NULL,
  importe         numeric(15,2) NOT NULL,
  moneda          bigint,
  estado          varchar(15)  NOT NULL DEFAULT 'PENDIENTE'
                    CHECK (estado IN ('PENDIENTE','CONCILIADO','APLICADO','VENCIDO')),
  movimiento      bigint       REFERENCES movimiento_bancario_importado,  -- movimiento que la concilio
  cobro           bigint       REFERENCES cobro,                          -- cobro cuando se aplica
  creado_en       timestamptz  NOT NULL DEFAULT now(),
  expira_en       timestamptz,
  usuario_creacion varchar(20), fecha_creacion timestamptz NOT NULL DEFAULT now(),
  version         bigint       NOT NULL DEFAULT 0
);
CREATE INDEX ix_ppq_estado ON portal_pago_qr (tenant, estado, creado_en);
-- La referencia es unica por tenant (es la que viaja en el QR y se cruza con el movimiento).
CREATE UNIQUE INDEX ux_ppq_ref ON portal_pago_qr (tenant, referencia);

ALTER TABLE portal_pago_qr ENABLE ROW LEVEL SECURITY;
ALTER TABLE portal_pago_qr FORCE ROW LEVEL SECURITY;
CREATE POLICY p_ppq_sel ON portal_pago_qr FOR SELECT USING (tenant = app_tenant() OR app_tenant() = -1);
CREATE POLICY p_ppq_ins ON portal_pago_qr FOR INSERT WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_ppq_upd ON portal_pago_qr FOR UPDATE USING (app_tenant() = -1 OR tenant = app_tenant()) WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_ppq_del ON portal_pago_qr FOR DELETE USING (app_tenant() = -1 OR tenant = app_tenant());
