-- ============================================================================
-- V62 - Portal: reclamos del cliente con fotos de su unidad (comprada o alquilada).
-- El cliente abre un reclamo (mantenimiento, dano, servicio...), describe y adjunta fotos.
-- Queda en bandeja interna donde un operador responde y cambia el estado. RLS por tenant.
-- ============================================================================

SELECT set_config('app.tenant', '-1', true);

INSERT INTO parametro_sistema (tenant, clave, valor, descripcion, tipo, grupo, valor_defecto, usuario_creacion, fecha_creacion)
  SELECT -1, 'RECLAMO_FOTO_TAMANO_MAX_MB', '8', 'Tamano maximo por foto de reclamo (MB)', 'ENTERO', 'Portal', '8', 'sistema', now()
  WHERE NOT EXISTS (SELECT 1 FROM parametro_sistema p WHERE p.clave='RECLAMO_FOTO_TAMANO_MAX_MB' AND p.tenant=-1);
INSERT INTO parametro_sistema (tenant, clave, valor, descripcion, tipo, grupo, valor_defecto, usuario_creacion, fecha_creacion)
  SELECT -1, 'RECLAMO_MAX_FOTOS', '6', 'Cantidad maxima de fotos por reclamo', 'ENTERO', 'Portal', '6', 'sistema', now()
  WHERE NOT EXISTS (SELECT 1 FROM parametro_sistema p WHERE p.clave='RECLAMO_MAX_FOTOS' AND p.tenant=-1);

CREATE TABLE reclamo (
  reclamo          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant           bigint      NOT NULL REFERENCES persona_juridica(persona),
  persona          bigint      NOT NULL REFERENCES persona(persona),
  operacion        bigint,
  unidad           varchar(160),
  tipo             varchar(20) NOT NULL DEFAULT 'OTRO'
                     CHECK (tipo IN ('MANTENIMIENTO','DANO','SERVICIO','ADMINISTRATIVO','OTRO')),
  titulo           varchar(160) NOT NULL,
  descripcion      varchar(2000),
  estado           varchar(15) NOT NULL DEFAULT 'ABIERTO'
                     CHECK (estado IN ('ABIERTO','EN_PROCESO','RESUELTO','RECHAZADO','CERRADO')),
  prioridad        varchar(10) NOT NULL DEFAULT 'MEDIA' CHECK (prioridad IN ('BAJA','MEDIA','ALTA')),
  respuesta        varchar(2000),
  usuario_revision varchar(20),
  fecha_revision   timestamptz,
  creado_en        timestamptz NOT NULL DEFAULT now(),
  version          bigint      NOT NULL DEFAULT 0
);
CREATE INDEX ix_reclamo_persona ON reclamo (tenant, persona, estado);
CREATE INDEX ix_reclamo_estado  ON reclamo (tenant, estado, creado_en);

CREATE TABLE reclamo_foto (
  reclamo_foto   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant         bigint      NOT NULL REFERENCES persona_juridica(persona),
  reclamo        bigint      NOT NULL REFERENCES reclamo(reclamo),
  archivo_nombre varchar(255),
  archivo_fisico varchar(120),
  archivo_mime   varchar(120),
  archivo_hash   varchar(64),
  archivo_tamano bigint,
  creado_en      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_reclamo_foto ON reclamo_foto (reclamo);

ALTER TABLE reclamo ENABLE ROW LEVEL SECURITY;
ALTER TABLE reclamo FORCE ROW LEVEL SECURITY;
CREATE POLICY p_reclamo_sel ON reclamo FOR SELECT USING (tenant = app_tenant() OR app_tenant() = -1);
CREATE POLICY p_reclamo_ins ON reclamo FOR INSERT WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_reclamo_upd ON reclamo FOR UPDATE USING (app_tenant() = -1 OR tenant = app_tenant()) WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());

ALTER TABLE reclamo_foto ENABLE ROW LEVEL SECURITY;
ALTER TABLE reclamo_foto FORCE ROW LEVEL SECURITY;
CREATE POLICY p_reclamo_foto_sel ON reclamo_foto FOR SELECT USING (tenant = app_tenant() OR app_tenant() = -1);
CREATE POLICY p_reclamo_foto_ins ON reclamo_foto FOR INSERT WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_reclamo_foto_upd ON reclamo_foto FOR UPDATE USING (app_tenant() = -1 OR tenant = app_tenant()) WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
