-- ============================================================================
-- V63 - Gestion interna del reclamo: recibir, priorizar, asignar, calendarizar, proveedor
-- (con cotizacion -> orden de pago), verificar con evidencia de fotos y cerrar. + bandeja/dashboard.
-- ============================================================================

SELECT set_config('app.tenant', '-1', true);

-- Pantalla interna de la bandeja de reclamos.
INSERT INTO entidad (lista, codigo, tenant, descripcion, usuario_creacion, fecha_creacion)
VALUES ('PANTALLAS', 'reclamos', -1, 'Gestion de reclamos (bandeja)', 'sistema', now())
ON CONFLICT (lista, codigo, tenant) DO NOTHING;

-- Campos de gestion en el reclamo.
ALTER TABLE reclamo ADD COLUMN asignado          varchar(60);
ALTER TABLE reclamo ADD COLUMN fecha_programada  date;
ALTER TABLE reclamo ADD COLUMN proveedor_nombre  varchar(160);
ALTER TABLE reclamo ADD COLUMN proveedor         bigint;
ALTER TABLE reclamo ADD COLUMN cotizacion        numeric(15,2);
ALTER TABLE reclamo ADD COLUMN moneda            bigint;
ALTER TABLE reclamo ADD COLUMN orden_pago        bigint;
ALTER TABLE reclamo ADD COLUMN cerrado_en        timestamptz;

-- Origen de la foto: CLIENTE (evidencia del reclamo) o SOLUCION (evidencia de la resolucion).
ALTER TABLE reclamo_foto ADD COLUMN origen varchar(12) NOT NULL DEFAULT 'CLIENTE';

-- Bitacora / seguimiento del reclamo (timeline visible).
CREATE TABLE reclamo_seguimiento (
  reclamo_seguimiento bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant     bigint      NOT NULL REFERENCES persona_juridica(persona),
  reclamo    bigint      NOT NULL REFERENCES reclamo(reclamo),
  tipo       varchar(20) NOT NULL DEFAULT 'NOTA'
               CHECK (tipo IN ('NOTA','ESTADO','ASIGNACION','PROGRAMACION','PROVEEDOR','ORDEN_PAGO','EVIDENCIA')),
  mensaje    varchar(600),
  usuario    varchar(60),
  creado_en  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_reclamo_seg ON reclamo_seguimiento (reclamo, creado_en);

-- Orden de pago liviana ligada al reclamo/proveedor (base para enlazar luego al motor de egresos).
CREATE TABLE reclamo_orden_pago (
  reclamo_orden_pago bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant           bigint       NOT NULL REFERENCES persona_juridica(persona),
  reclamo          bigint       NOT NULL REFERENCES reclamo(reclamo),
  proveedor_nombre varchar(160),
  proveedor        bigint,
  concepto         varchar(200),
  monto            numeric(15,2) NOT NULL,
  moneda           bigint,
  estado           varchar(15)  NOT NULL DEFAULT 'GENERADA' CHECK (estado IN ('GENERADA','PAGADA','ANULADA')),
  usuario          varchar(60),
  creado_en        timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX ix_reclamo_op ON reclamo_orden_pago (tenant, estado, creado_en);

ALTER TABLE reclamo_seguimiento ENABLE ROW LEVEL SECURITY;
ALTER TABLE reclamo_seguimiento FORCE ROW LEVEL SECURITY;
CREATE POLICY p_rseg_sel ON reclamo_seguimiento FOR SELECT USING (tenant = app_tenant() OR app_tenant() = -1);
CREATE POLICY p_rseg_ins ON reclamo_seguimiento FOR INSERT WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());

ALTER TABLE reclamo_orden_pago ENABLE ROW LEVEL SECURITY;
ALTER TABLE reclamo_orden_pago FORCE ROW LEVEL SECURITY;
CREATE POLICY p_rop_sel ON reclamo_orden_pago FOR SELECT USING (tenant = app_tenant() OR app_tenant() = -1);
CREATE POLICY p_rop_ins ON reclamo_orden_pago FOR INSERT WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
CREATE POLICY p_rop_upd ON reclamo_orden_pago FOR UPDATE USING (app_tenant() = -1 OR tenant = app_tenant()) WITH CHECK (app_tenant() = -1 OR tenant = app_tenant());
