-- V6 (REQ-0004): permisos por ACCION, no solo por pantalla.
-- Regla: perfil ADMINISTRADOR tiene todos los permisos implicitos; el perfil USUARIO
-- solo puede lo que se le otorga explicitamente aqui. pantalla '*' = todas las pantallas.
-- Acciones (enum cerrado en Java): VER, CREAR, EDITAR, INACTIVAR, REACTIVAR, EXPORTAR, VER_AUDITORIA.
-- Los datos de auditoria (usuario/fecha de modificacion, historial futuro) solo se muestran
-- con VER_AUDITORIA (decision del usuario 2026-07-05).

CREATE TABLE permiso_usuario (
  permiso_usuario bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario  bigint      NOT NULL REFERENCES usuario,
  pantalla varchar(60) NOT NULL,             -- id de vista sin .xhtml (ej. 'articulos') o '*'
  accion   varchar(30) NOT NULL CHECK (accion IN
           ('VER','CREAR','EDITAR','INACTIVAR','REACTIVAR','EXPORTAR','VER_AUDITORIA')),
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  version bigint NOT NULL DEFAULT 0,
  UNIQUE (usuario, pantalla, accion)
);
