-- V7 (REQ-0004): preferencias por usuario ("Mi vista"), cambio de contrasena obligatorio
-- al primer ingreso y lista de pantallas para administrar permisos.

CREATE TABLE preferencia_usuario (
  preferencia_usuario bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario  bigint       NOT NULL REFERENCES usuario,
  pantalla varchar(60)  NOT NULL,
  clave    varchar(80)  NOT NULL,          -- ej. 'mi_vista'
  valor    text         NOT NULL,          -- JSON (columnas, orden, filtros, filas)
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  version bigint NOT NULL DEFAULT 0,
  UNIQUE (usuario, pantalla, clave)
);

-- Cambio de contrasena obligatorio: true por defecto para usuarios NUEVOS (ABM de usuarios
-- y reseteo de contrasena); los usuarios ya existentes no quedan forzados retroactivamente.
ALTER TABLE usuario ADD COLUMN debe_cambiar_password boolean NOT NULL DEFAULT true;
UPDATE usuario SET debe_cambiar_password = false;

-- Pantallas del sistema (para el combo de permisos del ABM de usuarios)
INSERT INTO entidad (entidad, codigo, descripcion, usuario_creacion, fecha_creacion) VALUES
  ('PANTALLAS', '*',         'Todas las pantallas', 'sistema', now()),
  ('PANTALLAS', 'articulos', 'Artículos',           'sistema', now()),
  ('PANTALLAS', 'usuarios',  'Usuarios y permisos', 'sistema', now());
