# -*- coding: utf-8 -*-
# Genera V26__multiempresa_esquema.sql desde el mapeo real del esquema vivo V25.
import io

L = []
def w(s=""): L.append(s)

w("-- ============================================================================")
w("-- V26 — Transformacion MULTIEMPRESA del esquema (doc 14 v2.2)")
w("-- Deriva de la estructura REAL V25 (pg_dump) + definiciones aprobadas.")
w("-- Idea: discriminador 'tenant' (FK persona_juridica); -1 = registro GLOBAL")
w("-- bloqueado (solo SUPERADMIN). Catalogo 'entidad' con PK numerica + tenant;")
w("-- las referencias *_lista/*_codigo pasan a UNA columna bigint FK a entidad.")
w("-- PostgreSQL aplica todo el DDL en una transaccion (Flyway).")
w("-- ============================================================================")
w()
w("-- ── FASE A: fila GLOBAL sentinel (-1) ───────────────────────────────────────")
w("INSERT INTO persona (persona, tipo_personeria, nombre, numero_documento, estado, usuario_creacion, fecha_creacion)")
w("  VALUES (-1, 'JURIDICA', 'GLOBAL', 'GLOBAL', 'ACTIVO', 'SISTEMA', now());")
w("INSERT INTO persona_juridica (persona, razon_social, usuario_creacion, fecha_creacion)")
w("  VALUES (-1, 'GLOBAL', 'SISTEMA', now());")
w()
w("-- v_persona depende de columnas que se dropean/mueven; se suelta ahora y se")
w("-- recrea al final (doc 14 §7, ya tenant-aware sobre persona_empresa).")
w("DROP VIEW IF EXISTS v_persona;")
w()
w("-- ── FASE B: rediseno de 'entidad' (PK numerica + tenant) ─────────────────────")
w("-- B1: soltar dinamicamente TODAS las FK que referencian entidad(entidad,codigo).")
w("DO $$ DECLARE r record; BEGIN")
w("  FOR r IN SELECT conname, conrelid::regclass AS tbl FROM pg_constraint")
w("           WHERE confrelid = 'public.entidad'::regclass AND contype = 'f' LOOP")
w("    EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', r.tbl, r.conname);")
w("  END LOOP;")
w("END $$;")
w("-- B2: PK vieja (entidad,codigo) fuera; la columna 'entidad' pasa a ser 'lista'.")
w("ALTER TABLE entidad DROP CONSTRAINT entidad_pkey;")
w("ALTER TABLE entidad RENAME COLUMN entidad TO lista;")
w("-- B3: nueva PK autonumerica + tenant (-1 = todas las listas semilla son globales).")
w("ALTER TABLE entidad ADD COLUMN entidad bigint GENERATED BY DEFAULT AS IDENTITY;")
w("ALTER TABLE entidad ADD COLUMN tenant bigint;")
w("UPDATE entidad SET tenant = -1;")
w("ALTER TABLE entidad ALTER COLUMN tenant SET NOT NULL;")
w("ALTER TABLE entidad ADD CONSTRAINT entidad_pkey PRIMARY KEY (entidad);")
w("ALTER TABLE entidad ADD CONSTRAINT entidad_tenant_fkey FOREIGN KEY (tenant) REFERENCES persona_juridica(persona);")
w("ALTER TABLE entidad ADD CONSTRAINT entidad_lista_codigo_tenant_key UNIQUE (lista, codigo, tenant);")
w("CREATE INDEX ix_entidad_lista_tenant ON entidad (lista, tenant);")
w()
w("-- ── FASE C: referencias *_lista/*_codigo -> UNA columna bigint FK a entidad ──")
w("-- (mapeo por (lista,codigo)->entidad.entidad; entidad ya tiene los ids asignados)")

# uniques a soltar antes de dropear columnas del par
w("ALTER TABLE atributo   DROP CONSTRAINT atributo_grupo_codigo_descripcion_key;")
w("ALTER TABLE persona_rol DROP CONSTRAINT persona_rol_persona_rol_lista_rol_codigo_key;")
w()

INPLACE = [
    ("activo","tipo",True),
    ("anulacion","motivo",True),
    ("articulo","categoria",False),
    ("articulo","unidad_medida",False),
    ("articulo","presentacion",False),
    ("articulo","marca",False),
    ("articulo","modelo",False),
    ("articulo","familia",False),
    ("articulo","grupo",False),
    ("articulo","subgrupo",False),
    ("articulo","procedencia",False),
    ("articulo_propiedad","propiedad",True),
    ("articulo_propiedad","referencia",False),
    ("atributo","grupo",True),
    ("atributo_por_tipo","tipo",True),
    ("dato_cobro","emisor",False),
    ("dato_cobro","procesador",False),
    ("dato_cobro","motivo_rechazo",False),
    ("ingreso_egreso","tipo_imputacion",False),
    ("liquidacion","motivo",True),
    ("operacion","tipo_contrato",False),
    ("operacion","tipo_financiacion",False),
    ("persona","tipo_documento",False),
    ("persona_rol","rol",True),
    ("ubicacion_geografica","nivel",True),
]
# persona_rol necesita el tenant por CASE(rol_codigo) ANTES de dropear el par -> se maneja aparte.
for t,c,nn in INPLACE:
    w(f"ALTER TABLE {t} ADD COLUMN {c} bigint;")
    if t=="persona_rol":
        # tenant segun rol identitario (EMPRESA global) antes de perder rol_codigo
        w("ALTER TABLE persona_rol ADD COLUMN tenant bigint;")
        w("UPDATE persona_rol SET tenant = CASE WHEN rol_codigo = 'EMPRESA' THEN -1 ELSE 1 END;")
    w(f"UPDATE {t} SET {c} = e.entidad FROM entidad e")
    w(f"  WHERE e.lista = {t}.{c}_lista AND e.codigo = {t}.{c}_codigo;")
    w(f"ALTER TABLE {t} DROP COLUMN {c}_lista;")
    w(f"ALTER TABLE {t} DROP COLUMN {c}_codigo;")
    if nn:
        w(f"ALTER TABLE {t} ALTER COLUMN {c} SET NOT NULL;")
    w(f"ALTER TABLE {t} ADD CONSTRAINT {t}_{c}_fkey FOREIGN KEY ({c}) REFERENCES entidad(entidad);")
    if t=="persona_rol":
        w("ALTER TABLE persona_rol ALTER COLUMN tenant SET NOT NULL;")
        w("ALTER TABLE persona_rol ADD CONSTRAINT persona_rol_tenant_fkey FOREIGN KEY (tenant) REFERENCES persona_juridica(persona);")
        w("ALTER TABLE persona_rol ADD CONSTRAINT persona_rol_persona_tenant_rol_key UNIQUE (persona, tenant, rol);")
        w("CREATE INDEX ix_persona_rol_tenant ON persona_rol (tenant, rol);")
    w()

w("-- ── FASE C2: tipo de comprobante = dominio DIRECTO varchar(25) (no catalogo) ──")
for t in ("documento","rango_comprobante"):
    w(f"ALTER TABLE {t} DROP COLUMN tipo_lista;")
    w(f"ALTER TABLE {t} RENAME COLUMN tipo_codigo TO tipo;")
    w(f"ALTER TABLE {t} ALTER COLUMN tipo TYPE varchar(25);")
w()

w("-- ── FASE D: RENAME empresa -> tenant (8 tablas) ─────────────────────────────")
for t in ("usuario","operacion","activo","planilla","cobro","ingreso_egreso","anulacion","rango_comprobante"):
    w(f"ALTER TABLE {t} RENAME COLUMN empresa TO tenant;")
w("-- activo.tenant era NULLABLE -> pasa a NOT NULL (0 filas; default de negocio = 1).")
w("UPDATE activo SET tenant = 1 WHERE tenant IS NULL;")
w("ALTER TABLE activo ALTER COLUMN tenant SET NOT NULL;")
w()

w("-- ── FASE E: documento gana tenant (dueno) y CONSERVA empresa (emisora) ──────")
w("ALTER TABLE documento ADD COLUMN tenant bigint;")
w("UPDATE documento SET tenant = empresa;")
w("ALTER TABLE documento ALTER COLUMN tenant SET NOT NULL;")
w("ALTER TABLE documento ADD CONSTRAINT documento_tenant_fkey FOREIGN KEY (tenant) REFERENCES persona_juridica(persona);")
w("ALTER TABLE documento DROP CONSTRAINT documento_empresa_tipo_codigo_serie_numero_key;")
w("ALTER TABLE documento ADD CONSTRAINT documento_tenant_empresa_tipo_serie_numero_key UNIQUE (tenant, empresa, tipo, serie, numero);")
w()

w("-- ── FASE F: persona_empresa (datos comerciales por tenant) ──────────────────")
w("""CREATE TABLE persona_empresa (
    persona_empresa      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    persona              bigint NOT NULL REFERENCES persona,
    tenant               bigint NOT NULL REFERENCES persona_juridica(persona),
    es_contribuyente     boolean NOT NULL DEFAULT false,
    clasificacion_fiscal varchar(20),
    direccion            varchar(180),
    telefono             varchar(20),
    email                varchar(180),
    ubicacion            bigint REFERENCES ubicacion_geografica,
    ubicacion_url        varchar(250),
    observacion          text,
    estado_civil         bigint REFERENCES entidad,
    nacionalidad         varchar(80),
    nombre_fantasia      varchar(120),
    representante_legal  bigint REFERENCES persona,
    actividad            bigint REFERENCES entidad,
    estado               varchar(10) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO')),
    usuario_creacion     varchar(20) NOT NULL,
    fecha_creacion       timestamptz NOT NULL,
    usuario_modificacion varchar(20),
    fecha_modificacion   timestamptz,
    version              bigint NOT NULL DEFAULT 0,
    UNIQUE (persona, tenant)
);
CREATE INDEX ix_persona_empresa_tenant ON persona_empresa (tenant);""")
w("-- Backfill: mover a tenant=1 los datos comerciales que vivian en persona/fisica/juridica.")
w("""INSERT INTO persona_empresa (persona, tenant, es_contribuyente, clasificacion_fiscal, direccion,
        telefono, email, ubicacion, ubicacion_url, observacion, estado_civil, nacionalidad,
        nombre_fantasia, representante_legal, actividad, estado, usuario_creacion, fecha_creacion)
SELECT p.persona, 1, p.es_contribuyente, p.clasificacion_fiscal, p.direccion,
       p.telefono, p.email, p.ubicacion, p.ubicacion_url, p.observacion,
       (SELECT e.entidad FROM entidad e WHERE e.lista = pf.estado_civil_lista AND e.codigo = pf.estado_civil_codigo),
       pf.nacionalidad, pj.nombre_fantasia, pj.representante_legal,
       (SELECT e.entidad FROM entidad e WHERE e.lista = pj.actividad_lista AND e.codigo = pj.actividad_codigo),
       'ACTIVO', 'SISTEMA', now()
FROM persona p
LEFT JOIN persona_fisica   pf ON pf.persona = p.persona
LEFT JOIN persona_juridica pj ON pj.persona = p.persona
WHERE p.persona <> -1;""")
w("-- Quitar de las tablas de identidad las columnas ya movidas.")
w("ALTER TABLE persona DROP COLUMN es_contribuyente, DROP COLUMN clasificacion_fiscal,")
w("    DROP COLUMN direccion, DROP COLUMN telefono, DROP COLUMN email, DROP COLUMN ubicacion,")
w("    DROP COLUMN ubicacion_url, DROP COLUMN observacion;")
w("ALTER TABLE persona_fisica DROP COLUMN estado_civil_lista, DROP COLUMN estado_civil_codigo, DROP COLUMN nacionalidad;")
w("ALTER TABLE persona_juridica DROP COLUMN nombre_fantasia, DROP COLUMN representante_legal,")
w("    DROP COLUMN actividad_lista, DROP COLUMN actividad_codigo;")
w()

w("-- ── FASE G: catalogos de negocio ganan tenant (semillas de sistema -> -1) ───")
for t in ("moneda","impuesto","forma_pago","articulo","atributo","atributo_por_tipo","ubicacion_geografica"):
    w(f"ALTER TABLE {t} ADD COLUMN tenant bigint;")
    w(f"UPDATE {t} SET tenant = -1;")
    w(f"ALTER TABLE {t} ALTER COLUMN tenant SET NOT NULL;")
    w(f"ALTER TABLE {t} ADD CONSTRAINT {t}_tenant_fkey FOREIGN KEY (tenant) REFERENCES persona_juridica(persona);")
w("-- Unicidades por tenant (las globales por-codigo romperian el multiempresa).")
w("ALTER TABLE forma_pago DROP CONSTRAINT forma_pago_codigo_key;")
w("ALTER TABLE forma_pago ADD CONSTRAINT forma_pago_tenant_codigo_key UNIQUE (tenant, codigo);")
w("ALTER TABLE articulo DROP CONSTRAINT articulo_codigo_key;")
w("ALTER TABLE articulo ADD CONSTRAINT articulo_tenant_codigo_key UNIQUE (tenant, codigo);")
w("ALTER TABLE articulo DROP CONSTRAINT articulo_aplicacion_key;")
w("CREATE UNIQUE INDEX ix_articulo_tenant_aplicacion ON articulo (tenant, aplicacion) WHERE aplicacion IS NOT NULL;")
w("ALTER TABLE atributo ADD CONSTRAINT atributo_tenant_grupo_descripcion_key UNIQUE (tenant, grupo, descripcion);")
w()

w("-- ── FASE H: parametro_sistema por tenant (PK (tenant,clave); -1 = defaults) ──")
w("ALTER TABLE parametro_sistema ADD COLUMN tenant bigint;")
w("UPDATE parametro_sistema SET tenant = -1;")
w("ALTER TABLE parametro_sistema ALTER COLUMN tenant SET NOT NULL;")
w("ALTER TABLE parametro_sistema DROP CONSTRAINT parametro_sistema_pkey;")
w("ALTER TABLE parametro_sistema ADD CONSTRAINT parametro_sistema_pkey PRIMARY KEY (tenant, clave);")
w("ALTER TABLE parametro_sistema ADD CONSTRAINT parametro_sistema_tenant_fkey FOREIGN KEY (tenant) REFERENCES persona_juridica(persona);")
w()

w("-- ── FASE I: sucursal y grupo ganan tenant ──────────────────────────────────")
w("ALTER TABLE sucursal ADD COLUMN tenant bigint;")
w("UPDATE sucursal SET tenant = persona_juridica;")
w("ALTER TABLE sucursal ALTER COLUMN tenant SET NOT NULL;")
w("ALTER TABLE sucursal ADD CONSTRAINT sucursal_tenant_fkey FOREIGN KEY (tenant) REFERENCES persona_juridica(persona);")
w("CREATE INDEX ix_sucursal_tenant ON sucursal (tenant);")
w("ALTER TABLE grupo ADD COLUMN tenant bigint;")
w("UPDATE grupo SET tenant = -1;")
w("ALTER TABLE grupo ALTER COLUMN tenant SET NOT NULL;")
w("ALTER TABLE grupo ADD CONSTRAINT grupo_tenant_fkey FOREIGN KEY (tenant) REFERENCES persona_juridica(persona);")
w("ALTER TABLE grupo DROP CONSTRAINT grupo_codigo_key;")
w("ALTER TABLE grupo ADD CONSTRAINT grupo_tenant_codigo_key UNIQUE (tenant, codigo);")
w()

w("-- ── FASE J: usuario (perfil SUPERADMIN + primer superadmin en tenant -1) ─────")
w("ALTER TABLE usuario DROP CONSTRAINT usuario_perfil_check;")
w("ALTER TABLE usuario ADD CONSTRAINT usuario_perfil_check")
w("  CHECK (perfil IN ('SUPERADMIN','ADMINISTRADOR','USUARIO'));")
w("-- Primer SUPERADMIN: reutiliza el hash del admin (misma clave), tenant global -1.")
w("INSERT INTO usuario (codigo_usuario, password_hash, perfil, estado, tenant, debe_cambiar_password, usuario_creacion, fecha_creacion)")
w("SELECT 'superadmin', u.password_hash, 'SUPERADMIN', 'ACTIVO', -1, true, 'SISTEMA', now()")
w("  FROM usuario u WHERE u.codigo_usuario = 'admin';")
w("CREATE INDEX ix_usuario_tenant ON usuario (tenant);")
w()

w("-- ── FASE K: indices por tenant en tablas transaccionales ────────────────────")
w("CREATE INDEX ix_activo_tenant         ON activo (tenant, estado);")
w("CREATE INDEX ix_operacion_tenant      ON operacion (tenant, estado);")
w("CREATE INDEX ix_planilla_tenant       ON planilla (tenant, estado);")
w("CREATE INDEX ix_cobro_tenant          ON cobro (tenant, fecha);")
w("CREATE INDEX ix_ingreso_egreso_tenant ON ingreso_egreso (tenant, fecha);")
w("CREATE INDEX ix_documento_tenant      ON documento (tenant, estado);")
w()
w("-- ── FASE L: vistas recreadas exponiendo tenant (doc 14 §7) ──────────────────")
w("-- v_persona: identidad + datos comerciales por tenant (persona_empresa).")
w("""CREATE VIEW v_persona AS
SELECT p.persona, p.tipo_personeria, p.nombre, p.numero_documento, p.digito_verificador,
       p.tipo_documento, p.estado,
       pe.tenant, pe.es_contribuyente, pe.clasificacion_fiscal, pe.direccion, pe.telefono,
       pe.email, pe.ubicacion, pe.ubicacion_url, pe.observacion, pe.estado_civil,
       pe.nacionalidad, pe.nombre_fantasia, pe.representante_legal, pe.actividad,
       pf.nombres, pf.apellidos, pf.sexo, pf.fecha_nacimiento,
       pj.razon_social, pj.fecha_constitucion
  FROM persona p
  LEFT JOIN persona_fisica   pf ON pf.persona = p.persona
  LEFT JOIN persona_juridica pj ON pj.persona = p.persona
  LEFT JOIN persona_empresa  pe ON pe.persona = p.persona;""")
w()
w("-- v_operacion_saldo: + tenant (desde operacion).")
w("""CREATE OR REPLACE VIEW v_operacion_saldo AS
SELECT o.operacion, o.cliente, o.monto_total_operacion,
       COALESCE(sum(c.monto), 0) AS total_cuotas,
       COALESCE(sum(c.saldo), 0) AS saldo_pendiente,
       COALESCE(sum(CASE WHEN c.estado = 'CANCELADO' THEN c.monto ELSE 0 END), 0) AS total_cancelado,
       count(c.cronograma_cuota) FILTER (WHERE c.estado = 'PENDIENTE') AS cuotas_pendientes,
       o.tenant
  FROM operacion o
  LEFT JOIN cronograma_cuota c ON c.operacion = o.operacion
  GROUP BY o.operacion, o.cliente, o.monto_total_operacion, o.tenant;""")
w()
w("-- RLS (ENABLE + POLICIES): fase F5/F3.5 (REQ-0037), no aqui.")

out = "\n".join(L) + "\n"
# Escribe en STAGING (junto a este script), NO en el path activo de Flyway (obs 244):
# db/migration lo ejecuta FlywayMigrator al arranque. La promocion a db/migration es
# manual (git mv), solo cuando F2+F3 formen la unidad desplegable. Ver README.md.
import os
path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "V26__multiempresa_esquema.sql")
with io.open(path, "w", encoding="utf-8", newline="\n") as f:
    f.write(out)
print("escrito (staging, fuera de Flyway):", path)
print("lineas:", out.count(chr(10)))
