-- ============================================================================
-- V26 — Transformacion MULTIEMPRESA del esquema (doc 14 v2.2)
-- Deriva de la estructura REAL V25 (pg_dump) + definiciones aprobadas.
-- Idea: discriminador 'tenant' (FK persona_juridica); -1 = registro GLOBAL
-- bloqueado (solo SUPERADMIN). Catalogo 'entidad' con PK numerica + tenant;
-- las referencias *_lista/*_codigo pasan a UNA columna bigint FK a entidad.
-- PostgreSQL aplica todo el DDL en una transaccion (Flyway).
-- ============================================================================

-- ── FASE A: fila GLOBAL sentinel (-1) ───────────────────────────────────────
INSERT INTO persona (persona, tipo_personeria, nombre, numero_documento, estado, usuario_creacion, fecha_creacion)
  VALUES (-1, 'JURIDICA', 'GLOBAL', 'GLOBAL', 'ACTIVO', 'SISTEMA', now());
INSERT INTO persona_juridica (persona, razon_social, usuario_creacion, fecha_creacion)
  VALUES (-1, 'GLOBAL', 'SISTEMA', now());

-- v_persona depende de columnas que se dropean/mueven; se suelta ahora y se
-- recrea al final (doc 14 §7, ya tenant-aware sobre persona_empresa).
DROP VIEW IF EXISTS v_persona;

-- ── FASE B: rediseno de 'entidad' (PK numerica + tenant) ─────────────────────
-- B1: soltar dinamicamente TODAS las FK que referencian entidad(entidad,codigo).
DO $$ DECLARE r record; BEGIN
  FOR r IN SELECT conname, conrelid::regclass AS tbl FROM pg_constraint
           WHERE confrelid = 'public.entidad'::regclass AND contype = 'f' LOOP
    EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', r.tbl, r.conname);
  END LOOP;
END $$;
-- B2: PK vieja (entidad,codigo) fuera; la columna 'entidad' pasa a ser 'lista'.
ALTER TABLE entidad DROP CONSTRAINT entidad_pkey;
ALTER TABLE entidad RENAME COLUMN entidad TO lista;
-- B3: nueva PK autonumerica + tenant (-1 = todas las listas semilla son globales).
ALTER TABLE entidad ADD COLUMN entidad bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE entidad ADD COLUMN tenant bigint;
UPDATE entidad SET tenant = -1;
ALTER TABLE entidad ALTER COLUMN tenant SET NOT NULL;
ALTER TABLE entidad ADD CONSTRAINT entidad_pkey PRIMARY KEY (entidad);
ALTER TABLE entidad ADD CONSTRAINT entidad_tenant_fkey FOREIGN KEY (tenant) REFERENCES persona_juridica(persona);
ALTER TABLE entidad ADD CONSTRAINT entidad_lista_codigo_tenant_key UNIQUE (lista, codigo, tenant);
CREATE INDEX ix_entidad_lista_tenant ON entidad (lista, tenant);

-- ── FASE C: referencias *_lista/*_codigo -> UNA columna bigint FK a entidad ──
-- (mapeo por (lista,codigo)->entidad.entidad; entidad ya tiene los ids asignados)
ALTER TABLE atributo   DROP CONSTRAINT atributo_grupo_codigo_descripcion_key;
ALTER TABLE persona_rol DROP CONSTRAINT persona_rol_persona_rol_lista_rol_codigo_key;

ALTER TABLE activo ADD COLUMN tipo bigint;
UPDATE activo SET tipo = e.entidad FROM entidad e
  WHERE e.lista = activo.tipo_lista AND e.codigo = activo.tipo_codigo;
ALTER TABLE activo DROP COLUMN tipo_lista;
ALTER TABLE activo DROP COLUMN tipo_codigo;
ALTER TABLE activo ALTER COLUMN tipo SET NOT NULL;
ALTER TABLE activo ADD CONSTRAINT activo_tipo_fkey FOREIGN KEY (tipo) REFERENCES entidad(entidad);

ALTER TABLE anulacion ADD COLUMN motivo bigint;
UPDATE anulacion SET motivo = e.entidad FROM entidad e
  WHERE e.lista = anulacion.motivo_lista AND e.codigo = anulacion.motivo_codigo;
ALTER TABLE anulacion DROP COLUMN motivo_lista;
ALTER TABLE anulacion DROP COLUMN motivo_codigo;
ALTER TABLE anulacion ALTER COLUMN motivo SET NOT NULL;
ALTER TABLE anulacion ADD CONSTRAINT anulacion_motivo_fkey FOREIGN KEY (motivo) REFERENCES entidad(entidad);

ALTER TABLE articulo ADD COLUMN categoria bigint;
UPDATE articulo SET categoria = e.entidad FROM entidad e
  WHERE e.lista = articulo.categoria_lista AND e.codigo = articulo.categoria_codigo;
ALTER TABLE articulo DROP COLUMN categoria_lista;
ALTER TABLE articulo DROP COLUMN categoria_codigo;
ALTER TABLE articulo ADD CONSTRAINT articulo_categoria_fkey FOREIGN KEY (categoria) REFERENCES entidad(entidad);

ALTER TABLE articulo ADD COLUMN unidad_medida bigint;
UPDATE articulo SET unidad_medida = e.entidad FROM entidad e
  WHERE e.lista = articulo.unidad_medida_lista AND e.codigo = articulo.unidad_medida_codigo;
ALTER TABLE articulo DROP COLUMN unidad_medida_lista;
ALTER TABLE articulo DROP COLUMN unidad_medida_codigo;
ALTER TABLE articulo ADD CONSTRAINT articulo_unidad_medida_fkey FOREIGN KEY (unidad_medida) REFERENCES entidad(entidad);

ALTER TABLE articulo ADD COLUMN presentacion bigint;
UPDATE articulo SET presentacion = e.entidad FROM entidad e
  WHERE e.lista = articulo.presentacion_lista AND e.codigo = articulo.presentacion_codigo;
ALTER TABLE articulo DROP COLUMN presentacion_lista;
ALTER TABLE articulo DROP COLUMN presentacion_codigo;
ALTER TABLE articulo ADD CONSTRAINT articulo_presentacion_fkey FOREIGN KEY (presentacion) REFERENCES entidad(entidad);

ALTER TABLE articulo ADD COLUMN marca bigint;
UPDATE articulo SET marca = e.entidad FROM entidad e
  WHERE e.lista = articulo.marca_lista AND e.codigo = articulo.marca_codigo;
ALTER TABLE articulo DROP COLUMN marca_lista;
ALTER TABLE articulo DROP COLUMN marca_codigo;
ALTER TABLE articulo ADD CONSTRAINT articulo_marca_fkey FOREIGN KEY (marca) REFERENCES entidad(entidad);

ALTER TABLE articulo ADD COLUMN modelo bigint;
UPDATE articulo SET modelo = e.entidad FROM entidad e
  WHERE e.lista = articulo.modelo_lista AND e.codigo = articulo.modelo_codigo;
ALTER TABLE articulo DROP COLUMN modelo_lista;
ALTER TABLE articulo DROP COLUMN modelo_codigo;
ALTER TABLE articulo ADD CONSTRAINT articulo_modelo_fkey FOREIGN KEY (modelo) REFERENCES entidad(entidad);

ALTER TABLE articulo ADD COLUMN familia bigint;
UPDATE articulo SET familia = e.entidad FROM entidad e
  WHERE e.lista = articulo.familia_lista AND e.codigo = articulo.familia_codigo;
ALTER TABLE articulo DROP COLUMN familia_lista;
ALTER TABLE articulo DROP COLUMN familia_codigo;
ALTER TABLE articulo ADD CONSTRAINT articulo_familia_fkey FOREIGN KEY (familia) REFERENCES entidad(entidad);

ALTER TABLE articulo ADD COLUMN grupo bigint;
UPDATE articulo SET grupo = e.entidad FROM entidad e
  WHERE e.lista = articulo.grupo_lista AND e.codigo = articulo.grupo_codigo;
ALTER TABLE articulo DROP COLUMN grupo_lista;
ALTER TABLE articulo DROP COLUMN grupo_codigo;
ALTER TABLE articulo ADD CONSTRAINT articulo_grupo_fkey FOREIGN KEY (grupo) REFERENCES entidad(entidad);

ALTER TABLE articulo ADD COLUMN subgrupo bigint;
UPDATE articulo SET subgrupo = e.entidad FROM entidad e
  WHERE e.lista = articulo.subgrupo_lista AND e.codigo = articulo.subgrupo_codigo;
ALTER TABLE articulo DROP COLUMN subgrupo_lista;
ALTER TABLE articulo DROP COLUMN subgrupo_codigo;
ALTER TABLE articulo ADD CONSTRAINT articulo_subgrupo_fkey FOREIGN KEY (subgrupo) REFERENCES entidad(entidad);

ALTER TABLE articulo ADD COLUMN procedencia bigint;
UPDATE articulo SET procedencia = e.entidad FROM entidad e
  WHERE e.lista = articulo.procedencia_lista AND e.codigo = articulo.procedencia_codigo;
ALTER TABLE articulo DROP COLUMN procedencia_lista;
ALTER TABLE articulo DROP COLUMN procedencia_codigo;
ALTER TABLE articulo ADD CONSTRAINT articulo_procedencia_fkey FOREIGN KEY (procedencia) REFERENCES entidad(entidad);

ALTER TABLE articulo_propiedad ADD COLUMN propiedad bigint;
UPDATE articulo_propiedad SET propiedad = e.entidad FROM entidad e
  WHERE e.lista = articulo_propiedad.propiedad_lista AND e.codigo = articulo_propiedad.propiedad_codigo;
ALTER TABLE articulo_propiedad DROP COLUMN propiedad_lista;
ALTER TABLE articulo_propiedad DROP COLUMN propiedad_codigo;
ALTER TABLE articulo_propiedad ALTER COLUMN propiedad SET NOT NULL;
ALTER TABLE articulo_propiedad ADD CONSTRAINT articulo_propiedad_propiedad_fkey FOREIGN KEY (propiedad) REFERENCES entidad(entidad);

ALTER TABLE articulo_propiedad ADD COLUMN referencia bigint;
UPDATE articulo_propiedad SET referencia = e.entidad FROM entidad e
  WHERE e.lista = articulo_propiedad.referencia_lista AND e.codigo = articulo_propiedad.referencia_codigo;
ALTER TABLE articulo_propiedad DROP COLUMN referencia_lista;
ALTER TABLE articulo_propiedad DROP COLUMN referencia_codigo;
ALTER TABLE articulo_propiedad ADD CONSTRAINT articulo_propiedad_referencia_fkey FOREIGN KEY (referencia) REFERENCES entidad(entidad);

ALTER TABLE atributo ADD COLUMN grupo bigint;
UPDATE atributo SET grupo = e.entidad FROM entidad e
  WHERE e.lista = atributo.grupo_lista AND e.codigo = atributo.grupo_codigo;
ALTER TABLE atributo DROP COLUMN grupo_lista;
ALTER TABLE atributo DROP COLUMN grupo_codigo;
ALTER TABLE atributo ALTER COLUMN grupo SET NOT NULL;
ALTER TABLE atributo ADD CONSTRAINT atributo_grupo_fkey FOREIGN KEY (grupo) REFERENCES entidad(entidad);

ALTER TABLE atributo_por_tipo ADD COLUMN tipo bigint;
UPDATE atributo_por_tipo SET tipo = e.entidad FROM entidad e
  WHERE e.lista = atributo_por_tipo.tipo_lista AND e.codigo = atributo_por_tipo.tipo_codigo;
ALTER TABLE atributo_por_tipo DROP COLUMN tipo_lista;
ALTER TABLE atributo_por_tipo DROP COLUMN tipo_codigo;
ALTER TABLE atributo_por_tipo ALTER COLUMN tipo SET NOT NULL;
ALTER TABLE atributo_por_tipo ADD CONSTRAINT atributo_por_tipo_tipo_fkey FOREIGN KEY (tipo) REFERENCES entidad(entidad);

ALTER TABLE dato_cobro ADD COLUMN emisor bigint;
UPDATE dato_cobro SET emisor = e.entidad FROM entidad e
  WHERE e.lista = dato_cobro.emisor_lista AND e.codigo = dato_cobro.emisor_codigo;
ALTER TABLE dato_cobro DROP COLUMN emisor_lista;
ALTER TABLE dato_cobro DROP COLUMN emisor_codigo;
ALTER TABLE dato_cobro ADD CONSTRAINT dato_cobro_emisor_fkey FOREIGN KEY (emisor) REFERENCES entidad(entidad);

ALTER TABLE dato_cobro ADD COLUMN procesador bigint;
UPDATE dato_cobro SET procesador = e.entidad FROM entidad e
  WHERE e.lista = dato_cobro.procesador_lista AND e.codigo = dato_cobro.procesador_codigo;
ALTER TABLE dato_cobro DROP COLUMN procesador_lista;
ALTER TABLE dato_cobro DROP COLUMN procesador_codigo;
ALTER TABLE dato_cobro ADD CONSTRAINT dato_cobro_procesador_fkey FOREIGN KEY (procesador) REFERENCES entidad(entidad);

ALTER TABLE dato_cobro ADD COLUMN motivo_rechazo bigint;
UPDATE dato_cobro SET motivo_rechazo = e.entidad FROM entidad e
  WHERE e.lista = dato_cobro.motivo_rechazo_lista AND e.codigo = dato_cobro.motivo_rechazo_codigo;
ALTER TABLE dato_cobro DROP COLUMN motivo_rechazo_lista;
ALTER TABLE dato_cobro DROP COLUMN motivo_rechazo_codigo;
ALTER TABLE dato_cobro ADD CONSTRAINT dato_cobro_motivo_rechazo_fkey FOREIGN KEY (motivo_rechazo) REFERENCES entidad(entidad);

ALTER TABLE ingreso_egreso ADD COLUMN tipo_imputacion bigint;
UPDATE ingreso_egreso SET tipo_imputacion = e.entidad FROM entidad e
  WHERE e.lista = ingreso_egreso.tipo_imputacion_lista AND e.codigo = ingreso_egreso.tipo_imputacion_codigo;
ALTER TABLE ingreso_egreso DROP COLUMN tipo_imputacion_lista;
ALTER TABLE ingreso_egreso DROP COLUMN tipo_imputacion_codigo;
ALTER TABLE ingreso_egreso ADD CONSTRAINT ingreso_egreso_tipo_imputacion_fkey FOREIGN KEY (tipo_imputacion) REFERENCES entidad(entidad);

ALTER TABLE liquidacion ADD COLUMN motivo bigint;
UPDATE liquidacion SET motivo = e.entidad FROM entidad e
  WHERE e.lista = liquidacion.motivo_lista AND e.codigo = liquidacion.motivo_codigo;
ALTER TABLE liquidacion DROP COLUMN motivo_lista;
ALTER TABLE liquidacion DROP COLUMN motivo_codigo;
ALTER TABLE liquidacion ALTER COLUMN motivo SET NOT NULL;
ALTER TABLE liquidacion ADD CONSTRAINT liquidacion_motivo_fkey FOREIGN KEY (motivo) REFERENCES entidad(entidad);

ALTER TABLE operacion ADD COLUMN tipo_contrato bigint;
UPDATE operacion SET tipo_contrato = e.entidad FROM entidad e
  WHERE e.lista = operacion.tipo_contrato_lista AND e.codigo = operacion.tipo_contrato_codigo;
ALTER TABLE operacion DROP COLUMN tipo_contrato_lista;
ALTER TABLE operacion DROP COLUMN tipo_contrato_codigo;
ALTER TABLE operacion ADD CONSTRAINT operacion_tipo_contrato_fkey FOREIGN KEY (tipo_contrato) REFERENCES entidad(entidad);

ALTER TABLE operacion ADD COLUMN tipo_financiacion bigint;
UPDATE operacion SET tipo_financiacion = e.entidad FROM entidad e
  WHERE e.lista = operacion.tipo_financiacion_lista AND e.codigo = operacion.tipo_financiacion_codigo;
ALTER TABLE operacion DROP COLUMN tipo_financiacion_lista;
ALTER TABLE operacion DROP COLUMN tipo_financiacion_codigo;
ALTER TABLE operacion ADD CONSTRAINT operacion_tipo_financiacion_fkey FOREIGN KEY (tipo_financiacion) REFERENCES entidad(entidad);

ALTER TABLE persona ADD COLUMN tipo_documento bigint;
UPDATE persona SET tipo_documento = e.entidad FROM entidad e
  WHERE e.lista = persona.tipo_documento_lista AND e.codigo = persona.tipo_documento_codigo;
ALTER TABLE persona DROP COLUMN tipo_documento_lista;
ALTER TABLE persona DROP COLUMN tipo_documento_codigo;
ALTER TABLE persona ADD CONSTRAINT persona_tipo_documento_fkey FOREIGN KEY (tipo_documento) REFERENCES entidad(entidad);

ALTER TABLE persona_rol ADD COLUMN rol bigint;
ALTER TABLE persona_rol ADD COLUMN tenant bigint;
UPDATE persona_rol SET tenant = CASE WHEN rol_codigo = 'EMPRESA' THEN -1 ELSE 1 END;
UPDATE persona_rol SET rol = e.entidad FROM entidad e
  WHERE e.lista = persona_rol.rol_lista AND e.codigo = persona_rol.rol_codigo;
ALTER TABLE persona_rol DROP COLUMN rol_lista;
ALTER TABLE persona_rol DROP COLUMN rol_codigo;
ALTER TABLE persona_rol ALTER COLUMN rol SET NOT NULL;
ALTER TABLE persona_rol ADD CONSTRAINT persona_rol_rol_fkey FOREIGN KEY (rol) REFERENCES entidad(entidad);
ALTER TABLE persona_rol ALTER COLUMN tenant SET NOT NULL;
ALTER TABLE persona_rol ADD CONSTRAINT persona_rol_tenant_fkey FOREIGN KEY (tenant) REFERENCES persona_juridica(persona);
ALTER TABLE persona_rol ADD CONSTRAINT persona_rol_persona_tenant_rol_key UNIQUE (persona, tenant, rol);
CREATE INDEX ix_persona_rol_tenant ON persona_rol (tenant, rol);

ALTER TABLE ubicacion_geografica ADD COLUMN nivel bigint;
UPDATE ubicacion_geografica SET nivel = e.entidad FROM entidad e
  WHERE e.lista = ubicacion_geografica.nivel_lista AND e.codigo = ubicacion_geografica.nivel_codigo;
ALTER TABLE ubicacion_geografica DROP COLUMN nivel_lista;
ALTER TABLE ubicacion_geografica DROP COLUMN nivel_codigo;
ALTER TABLE ubicacion_geografica ALTER COLUMN nivel SET NOT NULL;
ALTER TABLE ubicacion_geografica ADD CONSTRAINT ubicacion_geografica_nivel_fkey FOREIGN KEY (nivel) REFERENCES entidad(entidad);

-- ── FASE C2: tipo de comprobante = dominio DIRECTO varchar(25) (no catalogo) ──
ALTER TABLE documento DROP COLUMN tipo_lista;
ALTER TABLE documento RENAME COLUMN tipo_codigo TO tipo;
ALTER TABLE documento ALTER COLUMN tipo TYPE varchar(25);
ALTER TABLE rango_comprobante DROP COLUMN tipo_lista;
ALTER TABLE rango_comprobante RENAME COLUMN tipo_codigo TO tipo;
ALTER TABLE rango_comprobante ALTER COLUMN tipo TYPE varchar(25);

-- ── FASE D: RENAME empresa -> tenant (8 tablas) ─────────────────────────────
ALTER TABLE usuario RENAME COLUMN empresa TO tenant;
ALTER TABLE operacion RENAME COLUMN empresa TO tenant;
ALTER TABLE activo RENAME COLUMN empresa TO tenant;
ALTER TABLE planilla RENAME COLUMN empresa TO tenant;
ALTER TABLE cobro RENAME COLUMN empresa TO tenant;
ALTER TABLE ingreso_egreso RENAME COLUMN empresa TO tenant;
ALTER TABLE anulacion RENAME COLUMN empresa TO tenant;
ALTER TABLE rango_comprobante RENAME COLUMN empresa TO tenant;
-- activo.tenant era NULLABLE -> pasa a NOT NULL (0 filas; default de negocio = 1).
UPDATE activo SET tenant = 1 WHERE tenant IS NULL;
ALTER TABLE activo ALTER COLUMN tenant SET NOT NULL;

-- ── FASE E: documento gana tenant (dueno) y CONSERVA empresa (emisora) ──────
ALTER TABLE documento ADD COLUMN tenant bigint;
UPDATE documento SET tenant = empresa;
ALTER TABLE documento ALTER COLUMN tenant SET NOT NULL;
ALTER TABLE documento ADD CONSTRAINT documento_tenant_fkey FOREIGN KEY (tenant) REFERENCES persona_juridica(persona);
ALTER TABLE documento DROP CONSTRAINT documento_empresa_tipo_codigo_serie_numero_key;
ALTER TABLE documento ADD CONSTRAINT documento_tenant_empresa_tipo_serie_numero_key UNIQUE (tenant, empresa, tipo, serie, numero);

-- ── FASE F: persona_empresa (datos comerciales por tenant) ──────────────────
CREATE TABLE persona_empresa (
    persona_empresa      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    persona              bigint NOT NULL REFERENCES persona,
    tenant               bigint NOT NULL REFERENCES persona_juridica(persona),
    es_contribuyente     boolean NOT NULL DEFAULT false,
    clasificacion_fiscal varchar(20),
    direccion            varchar(180),
    telefono             varchar(20),
    email                varchar(180),
    ubicacion            bigint REFERENCES ubicacion_geografica,
    ubicacion_url        varchar(250),
    observacion          text,
    estado_civil         bigint REFERENCES entidad,
    nacionalidad         varchar(80),
    nombre_fantasia      varchar(120),
    representante_legal  bigint REFERENCES persona,
    actividad            bigint REFERENCES entidad,
    estado               varchar(10) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO')),
    usuario_creacion     varchar(20) NOT NULL,
    fecha_creacion       timestamptz NOT NULL,
    usuario_modificacion varchar(20),
    fecha_modificacion   timestamptz,
    version              bigint NOT NULL DEFAULT 0,
    UNIQUE (persona, tenant)
);
CREATE INDEX ix_persona_empresa_tenant ON persona_empresa (tenant);
-- Backfill: mover a tenant=1 los datos comerciales que vivian en persona/fisica/juridica.
INSERT INTO persona_empresa (persona, tenant, es_contribuyente, clasificacion_fiscal, direccion,
        telefono, email, ubicacion, ubicacion_url, observacion, estado_civil, nacionalidad,
        nombre_fantasia, representante_legal, actividad, estado, usuario_creacion, fecha_creacion)
SELECT p.persona, 1, p.es_contribuyente, p.clasificacion_fiscal, p.direccion,
       p.telefono, p.email, p.ubicacion, p.ubicacion_url, p.observacion,
       (SELECT e.entidad FROM entidad e WHERE e.lista = pf.estado_civil_lista AND e.codigo = pf.estado_civil_codigo),
       pf.nacionalidad, pj.nombre_fantasia, pj.representante_legal,
       (SELECT e.entidad FROM entidad e WHERE e.lista = pj.actividad_lista AND e.codigo = pj.actividad_codigo),
       'ACTIVO', 'SISTEMA', now()
FROM persona p
LEFT JOIN persona_fisica   pf ON pf.persona = p.persona
LEFT JOIN persona_juridica pj ON pj.persona = p.persona
WHERE p.persona <> -1;
-- Quitar de las tablas de identidad las columnas ya movidas.
ALTER TABLE persona DROP COLUMN es_contribuyente, DROP COLUMN clasificacion_fiscal,
    DROP COLUMN direccion, DROP COLUMN telefono, DROP COLUMN email, DROP COLUMN ubicacion,
    DROP COLUMN ubicacion_url, DROP COLUMN observacion;
ALTER TABLE persona_fisica DROP COLUMN estado_civil_lista, DROP COLUMN estado_civil_codigo, DROP COLUMN nacionalidad;
ALTER TABLE persona_juridica DROP COLUMN nombre_fantasia, DROP COLUMN representante_legal,
    DROP COLUMN actividad_lista, DROP COLUMN actividad_codigo;

-- ── FASE G: catalogos de negocio ganan tenant (semillas de sistema -> -1) ───
ALTER TABLE moneda ADD COLUMN tenant bigint;
UPDATE moneda SET tenant = -1;
ALTER TABLE moneda ALTER COLUMN tenant SET NOT NULL;
ALTER TABLE moneda ADD CONSTRAINT moneda_tenant_fkey FOREIGN KEY (tenant) REFERENCES persona_juridica(persona);
ALTER TABLE impuesto ADD COLUMN tenant bigint;
UPDATE impuesto SET tenant = -1;
ALTER TABLE impuesto ALTER COLUMN tenant SET NOT NULL;
ALTER TABLE impuesto ADD CONSTRAINT impuesto_tenant_fkey FOREIGN KEY (tenant) REFERENCES persona_juridica(persona);
ALTER TABLE forma_pago ADD COLUMN tenant bigint;
UPDATE forma_pago SET tenant = -1;
ALTER TABLE forma_pago ALTER COLUMN tenant SET NOT NULL;
ALTER TABLE forma_pago ADD CONSTRAINT forma_pago_tenant_fkey FOREIGN KEY (tenant) REFERENCES persona_juridica(persona);
ALTER TABLE articulo ADD COLUMN tenant bigint;
UPDATE articulo SET tenant = -1;
ALTER TABLE articulo ALTER COLUMN tenant SET NOT NULL;
ALTER TABLE articulo ADD CONSTRAINT articulo_tenant_fkey FOREIGN KEY (tenant) REFERENCES persona_juridica(persona);
ALTER TABLE atributo ADD COLUMN tenant bigint;
UPDATE atributo SET tenant = -1;
ALTER TABLE atributo ALTER COLUMN tenant SET NOT NULL;
ALTER TABLE atributo ADD CONSTRAINT atributo_tenant_fkey FOREIGN KEY (tenant) REFERENCES persona_juridica(persona);
ALTER TABLE atributo_por_tipo ADD COLUMN tenant bigint;
UPDATE atributo_por_tipo SET tenant = -1;
ALTER TABLE atributo_por_tipo ALTER COLUMN tenant SET NOT NULL;
ALTER TABLE atributo_por_tipo ADD CONSTRAINT atributo_por_tipo_tenant_fkey FOREIGN KEY (tenant) REFERENCES persona_juridica(persona);
ALTER TABLE ubicacion_geografica ADD COLUMN tenant bigint;
UPDATE ubicacion_geografica SET tenant = -1;
ALTER TABLE ubicacion_geografica ALTER COLUMN tenant SET NOT NULL;
ALTER TABLE ubicacion_geografica ADD CONSTRAINT ubicacion_geografica_tenant_fkey FOREIGN KEY (tenant) REFERENCES persona_juridica(persona);
-- Unicidades por tenant (las globales por-codigo romperian el multiempresa).
ALTER TABLE forma_pago DROP CONSTRAINT forma_pago_codigo_key;
ALTER TABLE forma_pago ADD CONSTRAINT forma_pago_tenant_codigo_key UNIQUE (tenant, codigo);
ALTER TABLE articulo DROP CONSTRAINT articulo_codigo_key;
ALTER TABLE articulo ADD CONSTRAINT articulo_tenant_codigo_key UNIQUE (tenant, codigo);
ALTER TABLE articulo DROP CONSTRAINT articulo_aplicacion_key;
CREATE UNIQUE INDEX ix_articulo_tenant_aplicacion ON articulo (tenant, aplicacion) WHERE aplicacion IS NOT NULL;
ALTER TABLE atributo ADD CONSTRAINT atributo_tenant_grupo_descripcion_key UNIQUE (tenant, grupo, descripcion);

-- ── FASE H: parametro_sistema por tenant (PK (tenant,clave); -1 = defaults) ──
ALTER TABLE parametro_sistema ADD COLUMN tenant bigint;
UPDATE parametro_sistema SET tenant = -1;
ALTER TABLE parametro_sistema ALTER COLUMN tenant SET NOT NULL;
ALTER TABLE parametro_sistema DROP CONSTRAINT parametro_sistema_pkey;
ALTER TABLE parametro_sistema ADD CONSTRAINT parametro_sistema_pkey PRIMARY KEY (tenant, clave);
ALTER TABLE parametro_sistema ADD CONSTRAINT parametro_sistema_tenant_fkey FOREIGN KEY (tenant) REFERENCES persona_juridica(persona);

-- ── FASE I: sucursal y grupo ganan tenant ──────────────────────────────────
ALTER TABLE sucursal ADD COLUMN tenant bigint;
UPDATE sucursal SET tenant = persona_juridica;
ALTER TABLE sucursal ALTER COLUMN tenant SET NOT NULL;
ALTER TABLE sucursal ADD CONSTRAINT sucursal_tenant_fkey FOREIGN KEY (tenant) REFERENCES persona_juridica(persona);
CREATE INDEX ix_sucursal_tenant ON sucursal (tenant);
ALTER TABLE grupo ADD COLUMN tenant bigint;
UPDATE grupo SET tenant = -1;
ALTER TABLE grupo ALTER COLUMN tenant SET NOT NULL;
ALTER TABLE grupo ADD CONSTRAINT grupo_tenant_fkey FOREIGN KEY (tenant) REFERENCES persona_juridica(persona);
ALTER TABLE grupo DROP CONSTRAINT grupo_codigo_key;
ALTER TABLE grupo ADD CONSTRAINT grupo_tenant_codigo_key UNIQUE (tenant, codigo);

-- ── FASE J: usuario (perfil SUPERADMIN + primer superadmin en tenant -1) ─────
ALTER TABLE usuario DROP CONSTRAINT usuario_perfil_check;
ALTER TABLE usuario ADD CONSTRAINT usuario_perfil_check
  CHECK (perfil IN ('SUPERADMIN','ADMINISTRADOR','USUARIO'));
-- Primer SUPERADMIN: reutiliza el hash del admin (misma clave), tenant global -1.
INSERT INTO usuario (codigo_usuario, password_hash, perfil, estado, tenant, debe_cambiar_password, usuario_creacion, fecha_creacion)
SELECT 'superadmin', u.password_hash, 'SUPERADMIN', 'ACTIVO', -1, true, 'SISTEMA', now()
  FROM usuario u WHERE u.codigo_usuario = 'admin';
CREATE INDEX ix_usuario_tenant ON usuario (tenant);

-- ── FASE K: indices por tenant en tablas transaccionales ────────────────────
CREATE INDEX ix_activo_tenant         ON activo (tenant, estado);
CREATE INDEX ix_operacion_tenant      ON operacion (tenant, estado);
CREATE INDEX ix_planilla_tenant       ON planilla (tenant, estado);
CREATE INDEX ix_cobro_tenant          ON cobro (tenant, fecha);
CREATE INDEX ix_ingreso_egreso_tenant ON ingreso_egreso (tenant, fecha);
CREATE INDEX ix_documento_tenant      ON documento (tenant, estado);

-- ── FASE L: vistas recreadas exponiendo tenant (doc 14 §7) ──────────────────
-- v_persona: identidad + datos comerciales por tenant (persona_empresa).
CREATE VIEW v_persona AS
SELECT p.persona, p.tipo_personeria, p.nombre, p.numero_documento, p.digito_verificador,
       p.tipo_documento, p.estado,
       pe.tenant, pe.es_contribuyente, pe.clasificacion_fiscal, pe.direccion, pe.telefono,
       pe.email, pe.ubicacion, pe.ubicacion_url, pe.observacion, pe.estado_civil,
       pe.nacionalidad, pe.nombre_fantasia, pe.representante_legal, pe.actividad,
       pf.nombres, pf.apellidos, pf.sexo, pf.fecha_nacimiento,
       pj.razon_social, pj.fecha_constitucion
  FROM persona p
  LEFT JOIN persona_fisica   pf ON pf.persona = p.persona
  LEFT JOIN persona_juridica pj ON pj.persona = p.persona
  LEFT JOIN persona_empresa  pe ON pe.persona = p.persona;

-- v_operacion_saldo: + tenant (desde operacion).
CREATE OR REPLACE VIEW v_operacion_saldo AS
SELECT o.operacion, o.cliente, o.monto_total_operacion,
       COALESCE(sum(c.monto), 0) AS total_cuotas,
       COALESCE(sum(c.saldo), 0) AS saldo_pendiente,
       COALESCE(sum(CASE WHEN c.estado = 'CANCELADO' THEN c.monto ELSE 0 END), 0) AS total_cancelado,
       count(c.cronograma_cuota) FILTER (WHERE c.estado = 'PENDIENTE') AS cuotas_pendientes,
       o.tenant
  FROM operacion o
  LEFT JOIN cronograma_cuota c ON c.operacion = o.operacion
  GROUP BY o.operacion, o.cliente, o.monto_total_operacion, o.tenant;

-- RLS (ENABLE + POLICIES): fase F5/F3.5 (REQ-0037), no aqui.
