# -*- coding: utf-8 -*-
"""
REQ-0107 - Crea 5 vistas en INMOBILIARIA.FDB (legado) con toda la logica derivada.
Asi Excel solo hace 'SELECT * FROM V_DATOS_*' (SQL trivial) y el driver ODBC 2.0.5 no choca con
las expresiones complejas (CASE, aritmetica de fechas): las evalua el motor Firebird nativo.

Respalda el .FDB antes de escribir. Usa fdb (cliente embebido). NO toca datos, solo agrega vistas.
"""
import os, shutil, datetime, sys

SP = r"C:/Users/everm/AppData/Local/Temp/claude/C--Users-everm-OneDrive-Documents-Datos-claude-semaforo-semaforo-adaptivo-desarrollo/a89655ce-0ba4-4159-82b6-6f74ec57e4a3/scratchpad"
FBDIR = SP + "/fb/fb25"
os.environ["FIREBIRD"] = FBDIR
os.environ["PATH"] = FBDIR + os.pathsep + os.environ.get("PATH", "")
import fdb
fdb.load_api(FBDIR + "/fbembed.dll")
FDB = r"C:/Users/everm/OneDrive/Documents/Datos/Sistemas/2R/Desarrollo/SGInmo/codigo fuente/inmobiliaria/Pysistemas/migracion/source/INMOBILIARIA.FDB"

VISTAS = {}

VISTAS["V_DATOS_CUOTA"] = """
CREATE VIEW V_DATOS_CUOTA (
  CRONOGRAMA_CUOTA_ID, NUMERO_CUOTA, FECHA_VENCIMIENTO, MONTO, SALDO, ESTADO_CUOTA, FECHA_CANCELACION,
  ANIO_VTO, MES_VTO, TRAMO_AGING, DIAS_MORA, TIPO_OPERACION, ESTADO_OPERACION, CLIENTE, ACTIVO,
  TIPO_ACTIVO, MONEDA) AS
SELECT cc.CRONOGRAMA_CUOTA_ID, cc.NUMERO_CUOTA, cc.FECHA_VENCIMIENTO, cc.MONTO,
       CASE WHEN cc.ESTADO='CANCELADO' THEN 0 ELSE cc.MONTO END,
       cc.ESTADO, cc.FECHA_CANCELACION,
       EXTRACT(YEAR FROM cc.FECHA_VENCIMIENTO), EXTRACT(MONTH FROM cc.FECHA_VENCIMIENTO),
       CASE WHEN cc.ESTADO='CANCELADO' THEN 'COBRADA'
            WHEN cc.FECHA_VENCIMIENTO >= CURRENT_DATE THEN 'POR VENCER'
            WHEN CURRENT_DATE - CAST(cc.FECHA_VENCIMIENTO AS DATE) <= 30 THEN '01-30'
            WHEN CURRENT_DATE - CAST(cc.FECHA_VENCIMIENTO AS DATE) <= 60 THEN '31-60'
            WHEN CURRENT_DATE - CAST(cc.FECHA_VENCIMIENTO AS DATE) <= 90 THEN '61-90'
            ELSE '90+' END,
       CASE WHEN cc.ESTADO<>'CANCELADO' AND cc.FECHA_VENCIMIENTO < CURRENT_DATE
            THEN CURRENT_DATE - CAST(cc.FECHA_VENCIMIENTO AS DATE) ELSE 0 END,
       op.TIPO_OPERACION, op.ESTADO, sn.RAZON_SOCIAL, COALESCE(pr.NOMBRE, en.NOMBRE),
       pr.TIPO, mo.MONEDA
FROM CRONOGRAMAS_CUOTAS cc
JOIN OPERACIONES_PROPIEDADES op ON op.OPERACION_PROPIEDAD_ID = cc.OPERACION_PROPIEDAD_ID
LEFT JOIN SOCIOS_NEGOCIOS sn ON sn.SOCIO_NEGOCIO_ID = op.SOCIO_NEGOCIO_ID
LEFT JOIN PROPIEDADES pr ON pr.PROPIEDAD_ID = op.PROPIEDAD_ID
LEFT JOIN ENTIDADES_INMOBILIARIAS en ON en.ENTIDAD_INMOBILIARIA_ID = op.ENTIDAD_INMOBILIARIA_ID
LEFT JOIN MONEDAS mo ON mo.MONEDA_ID = cc.MONEDA_ID
"""

VISTAS["V_DATOS_COBRO"] = """
CREATE VIEW V_DATOS_COBRO (
  CRONOGRAMA_CUOTA_ID, MONTO, FECHA_COBRO, ANIO, MES, TIPO_OPERACION, CLIENTE, ACTIVO, MONEDA) AS
SELECT cc.CRONOGRAMA_CUOTA_ID, cc.MONTO,
       COALESCE(cc.FECHA_CANCELACION, cc.FECHA_VENCIMIENTO),
       EXTRACT(YEAR FROM COALESCE(cc.FECHA_CANCELACION, cc.FECHA_VENCIMIENTO)),
       EXTRACT(MONTH FROM COALESCE(cc.FECHA_CANCELACION, cc.FECHA_VENCIMIENTO)),
       op.TIPO_OPERACION, sn.RAZON_SOCIAL, COALESCE(pr.NOMBRE, en.NOMBRE), mo.MONEDA
FROM CRONOGRAMAS_CUOTAS cc
JOIN OPERACIONES_PROPIEDADES op ON op.OPERACION_PROPIEDAD_ID = cc.OPERACION_PROPIEDAD_ID
LEFT JOIN SOCIOS_NEGOCIOS sn ON sn.SOCIO_NEGOCIO_ID = op.SOCIO_NEGOCIO_ID
LEFT JOIN PROPIEDADES pr ON pr.PROPIEDAD_ID = op.PROPIEDAD_ID
LEFT JOIN ENTIDADES_INMOBILIARIAS en ON en.ENTIDAD_INMOBILIARIA_ID = op.ENTIDAD_INMOBILIARIA_ID
LEFT JOIN MONEDAS mo ON mo.MONEDA_ID = cc.MONEDA_ID
WHERE cc.ESTADO='CANCELADO'
"""

VISTAS["V_DATOS_ACTIVO"] = """
CREATE VIEW V_DATOS_ACTIVO (
  ACTIVO_ID, ACTIVO, TIPO_ACTIVO, DIRECCION, PRECIO_ALQUILER, PRECIO_VENTA, ESTADO_ACTIVO,
  SITUACION, EDIFICIO, NIVEL) AS
SELECT pr.PROPIEDAD_ID, pr.NOMBRE, pr.TIPO, pr.DIRECCION, pr.PRECIO_ALQUILER, pr.PRECIO_VENTA, pr.ESTADO,
       CASE WHEN pr.VENDIDA='S' THEN 'VENDIDA'
            WHEN EXISTS (SELECT 1 FROM OPERACIONES_PROPIEDADES o
                          WHERE o.PROPIEDAD_ID=pr.PROPIEDAD_ID AND o.ESTADO='VIGENTE'
                            AND o.TIPO_OPERACION LIKE 'ALQ%') THEN 'OCUPADA'
            WHEN pr.PRECIO_ALQUILER > 0 THEN 'VACANTE ALQUILABLE'
            ELSE 'LIBRE NO ALQUILABLE' END,
       en.NOMBRE, 'PROPIEDAD'
FROM PROPIEDADES pr
LEFT JOIN ENTIDADES_INMOBILIARIAS en ON en.ENTIDAD_INMOBILIARIA_ID = pr.ENTIDAD_INMOBILIARIA_ID
UNION ALL
SELECT en.ENTIDAD_INMOBILIARIA_ID, en.NOMBRE, en.TIPO, en.DIRECCION, 0, 0, en.ESTADO,
       'EDIFICIO/COMPLEJO', CAST(NULL AS VARCHAR(120)), 'ENTIDAD'
FROM ENTIDADES_INMOBILIARIAS en
"""

VISTAS["V_DATOS_MOVIMIENTO"] = """
CREATE VIEW V_DATOS_MOVIMIENTO (
  INGRESO_EGRESO_ID, FECHA, TIPO_MOVIMIENTO, ESTADO_MOV, MONTO, MONTO_NETO, ANIO, MES,
  CONCEPTO, PERSONA, ACTIVO, TIPO_IMPUTACION) AS
SELECT ie.INGRESO_EGRESO_ID, ie.FECHA, ie.TIPO, ie.ESTADO, ie.MONTO,
       CASE WHEN ie.TIPO='INGRESO' THEN ie.MONTO ELSE -ie.MONTO END,
       EXTRACT(YEAR FROM ie.FECHA), EXTRACT(MONTH FROM ie.FECHA),
       it.ITEM, sn.RAZON_SOCIAL, COALESCE(pr.NOMBRE, en.NOMBRE), ie.TIPO_IMPUTACION
FROM INGRESOS_EGRESOS ie
LEFT JOIN ITEMS_INGRESOS_EGRESOS it ON it.ITEM_INGRESO_EGRESO_ID = ie.ITEM_INGRESO_EGRESO_ID
LEFT JOIN SOCIOS_NEGOCIOS sn ON sn.SOCIO_NEGOCIO_ID = ie.SOCIO_NEGOCIO_ID
LEFT JOIN PROPIEDADES pr ON pr.PROPIEDAD_ID = ie.PROPIEDAD_ID
LEFT JOIN ENTIDADES_INMOBILIARIAS en ON en.ENTIDAD_INMOBILIARIA_ID = ie.ENTIDAD_INMOBILIARIA_ID
"""

VISTAS["V_DATOS_CONTRATO"] = """
CREATE VIEW V_DATOS_CONTRATO (
  OPERACION, TIPO_OPERACION, ESTADO_OPERACION, FECHA_OPERACION, FECHA_FIN_CONTRATO,
  MONTO_TOTAL_OPERACION, DIAS_PARA_VENCER, CLIENTE, ACTIVO,
  CUOTAS_TOTAL, CUOTAS_COBRADAS, MONTO_CRONOGRAMA, MONTO_COBRADO) AS
SELECT op.OPERACION_PROPIEDAD_ID, op.TIPO_OPERACION, op.ESTADO, op.FECHA_OPERACION, op.FECHA_FIN_CONTRATO,
       op.MONTO_TOTAL_OPERACION,
       CASE WHEN op.FECHA_FIN_CONTRATO IS NOT NULL THEN CAST(op.FECHA_FIN_CONTRATO AS DATE) - CURRENT_DATE END,
       sn.RAZON_SOCIAL, COALESCE(pr.NOMBRE, en.NOMBRE),
       cr.CUOTAS_TOTAL, cr.CUOTAS_COBRADAS, cr.MONTO_CRONOGRAMA, cr.MONTO_COBRADO
FROM OPERACIONES_PROPIEDADES op
LEFT JOIN SOCIOS_NEGOCIOS sn ON sn.SOCIO_NEGOCIO_ID = op.SOCIO_NEGOCIO_ID
LEFT JOIN PROPIEDADES pr ON pr.PROPIEDAD_ID = op.PROPIEDAD_ID
LEFT JOIN ENTIDADES_INMOBILIARIAS en ON en.ENTIDAD_INMOBILIARIA_ID = op.ENTIDAD_INMOBILIARIA_ID
LEFT JOIN (SELECT OPERACION_PROPIEDAD_ID, COUNT(*) CUOTAS_TOTAL,
                  SUM(CASE WHEN ESTADO='CANCELADO' THEN 1 ELSE 0 END) CUOTAS_COBRADAS,
                  SUM(MONTO) MONTO_CRONOGRAMA,
                  SUM(CASE WHEN ESTADO='CANCELADO' THEN MONTO ELSE 0 END) MONTO_COBRADO
           FROM CRONOGRAMAS_CUOTAS GROUP BY OPERACION_PROPIEDAD_ID) cr
       ON cr.OPERACION_PROPIEDAD_ID = op.OPERACION_PROPIEDAD_ID
"""

def main():
    # 1) backup
    if not os.path.exists(FDB):
        sys.exit("No existe el FDB: " + FDB)
    bak = FDB + "." + datetime.datetime.now().strftime("%Y%m%d_%H%M%S") + ".bak"
    shutil.copy2(FDB, bak)
    print("Backup:", bak, "(%.1f MB)" % (os.path.getsize(bak) / 1048576))

    con = fdb.connect(database=FDB, user="SYSDBA", password="masterkey", charset="WIN1252")
    cur = con.cursor()
    # vistas existentes
    cur.execute("SELECT TRIM(RDB$RELATION_NAME) FROM RDB$RELATIONS WHERE RDB$VIEW_BLR IS NOT NULL")
    existentes = set(r[0] for r in cur.fetchall())

    for nombre, ddl in VISTAS.items():
        if nombre in existentes:
            cur.execute("DROP VIEW " + nombre); con.commit(); print("  drop vista previa", nombre)
        cur.execute(ddl); con.commit()
        cur.execute("SELECT COUNT(*) FROM " + nombre)
        print("  OK  %-20s %d filas" % (nombre, cur.fetchone()[0]))
    con.close()
    print("\nVistas creadas. Excel ahora solo hace SELECT * FROM V_DATOS_*.")

if __name__ == "__main__":
    main()
