-- ONEsystem-security: esquema de referencia (PostgreSQL) para proyectos NUEVOS.
-- SGInmo ya lo tiene aplicado via sus migraciones V1/V5/V6/V7/V10/V11.
-- Convenciones: nombres en singular, PK = nombre de tabla, auditoria + version en todas.
-- `empresa` y `persona` son columnas LIBRES (bigint): cada proyecto decide si les pone FK.

CREATE TABLE usuario (
  usuario bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_usuario varchar(20) NOT NULL UNIQUE,
  password_hash varchar(100) NOT NULL,                -- bcrypt
  perfil varchar(20) NOT NULL CHECK (perfil IN ('ADMINISTRADOR','USUARIO')),
  estado varchar(10) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO')),
  empresa bigint,                                     -- opcional (SGInmo: FK a persona_juridica)
  persona bigint,                                     -- opcional
  intentos_fallidos smallint NOT NULL DEFAULT 0,
  bloqueado_hasta timestamptz,
  debe_cambiar_password boolean NOT NULL DEFAULT true,
  email varchar(180),                                 -- alertas y validacion de dos pasos
  telefono varchar(30),
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  version bigint NOT NULL DEFAULT 0
);

CREATE TABLE grupo (
  grupo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo varchar(30) NOT NULL UNIQUE,
  descripcion varchar(120) NOT NULL,
  estado varchar(10) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO')),
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  version bigint NOT NULL DEFAULT 0
);

CREATE TABLE usuario_grupo (
  usuario_grupo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario bigint NOT NULL REFERENCES usuario,
  grupo   bigint NOT NULL REFERENCES grupo,
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  version bigint NOT NULL DEFAULT 0,
  UNIQUE (usuario, grupo)
);

CREATE TABLE permiso_usuario (
  permiso_usuario bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario  bigint      NOT NULL REFERENCES usuario,
  pantalla varchar(60) NOT NULL,                      -- id de vista sin .xhtml o '*'
  accion   varchar(30) NOT NULL CHECK (accion IN
           ('OPERAR','VER','CREAR','EDITAR','INACTIVAR','REACTIVAR','EXPORTAR','VER_AUDITORIA')),
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  version bigint NOT NULL DEFAULT 0,
  UNIQUE (usuario, pantalla, accion)
);

CREATE TABLE permiso_grupo (
  permiso_grupo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  grupo    bigint      NOT NULL REFERENCES grupo,
  pantalla varchar(60) NOT NULL,
  accion   varchar(30) NOT NULL CHECK (accion IN
           ('OPERAR','VER','CREAR','EDITAR','INACTIVAR','REACTIVAR','EXPORTAR','VER_AUDITORIA')),
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  version bigint NOT NULL DEFAULT 0,
  UNIQUE (grupo, pantalla, accion)
);

CREATE TABLE preferencia_usuario (
  preferencia_usuario bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario  bigint       NOT NULL REFERENCES usuario,
  pantalla varchar(60)  NOT NULL,
  clave    varchar(80)  NOT NULL,                     -- ej. 'mi_vista'
  valor    text         NOT NULL,                     -- JSON
  usuario_creacion varchar(20) NOT NULL, fecha_creacion timestamptz NOT NULL,
  usuario_modificacion varchar(20), fecha_modificacion timestamptz,
  version bigint NOT NULL DEFAULT 0,
  UNIQUE (usuario, pantalla, clave)
);

-- Parametros que consume el modulo via ProveedorParametros (opcionales, con defaults):
-- LOGIN_MAX_INTENTOS='5', LOGIN_BLOQUEO_MINUTOS='15', ALERTA_LOGIN_FALLIDO='SI',
-- SMTP_HOST, SMTP_PUERTO='587', SMTP_USUARIO, SMTP_CLAVE, SMTP_DESDE, SMTP_TLS='SI'.
